#Requires -Version 5.1

<#
.SYNOPSIS
Bootstrap or update a GRM Custom Spec Kit workspace.

.DESCRIPTION
Creates or updates a validation workspace for GRM Custom Spec Kit.

Supported modes:
- FailIfExists: safe default. Fails when target directory already exists.
- CleanInstall: creates a clean workspace. If target exists, requires -Force and deletes it.
- UpdateExisting: updates an existing workspace non-destructively. Does not run specify init by default.

Deterministic Spec Kit initialization for CleanInstall:
- specify init --here --integration copilot --script ps --force

Runtime merge policy:
- Does NOT delete .github or .specify generated by Spec Kit, except during an explicit CleanInstall -Force.
- Copies GRM source-of-truth assets into the target.
- Merges runtime files over the clean or existing runtime where names match.
- Preserves additional standard Spec Kit runtime files introduced by the installed version.
- Installs corporate workflows from presets/grm-corporate-governance/workflows into .specify/workflows.
- Merges workflow-registry.json additively, preserving native entries such as speckit.
- Generates installation-report.md in both successful and failed executions.

.EXAMPLES
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01 -InstallMode CleanInstall -Force
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01 -InstallMode UpdateExisting
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01 -Branch main -KeepSourceCache
#>

[CmdletBinding()]
param(
    [string]$Root = "C:\dev\proys",
    [string]$TargetName,
    [string]$SourceRepoUrl = "https://github.com/sesanchezromeu/grm-custom-spec-kit.git",
    [string]$Branch = "main",
    [string]$Integration = "copilot",
    [string]$ScriptType = "ps",
    [ValidateSet("FailIfExists", "CleanInstall", "UpdateExisting")]
    [string]$InstallMode = "FailIfExists",
    [switch]$Force,
    [switch]$KeepSourceCache,
    [switch]$SkipGitInit,
    [switch]$CreateBranch,
    [string]$BranchName = "chore/e2e-clean-install"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([string]$Message)
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Write-Warn2 {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Assert-Command {
    param([string]$CommandName)
    if (-not (Get-Command $CommandName -ErrorAction SilentlyContinue)) {
        throw "Required command not found in PATH: $CommandName"
    }
}

function Get-CommandVersionSafe {
    param([string]$CommandName, [string[]]$Arguments)
    try {
        $output = & $CommandName @Arguments 2>&1 | Select-Object -First 1
        if ([string]::IsNullOrWhiteSpace(($output | Out-String))) {
            return "unknown"
        }
        return ($output | Out-String).Trim()
    }
    catch {
        return "unknown"
    }
}

function Copy-DirectoryMerge {
    param(
        [string]$From,
        [string]$To,
        [string]$Label,
        [System.Collections.Generic.List[string]]$Warnings,
        [string[]]$ExcludeDirectoryNames = @()
    )

    if (-not (Test-Path $From)) {
        $Warnings.Add("$Label source not found: $From")
        return $false
    }

    if (-not (Test-Path $To)) {
        New-Item -ItemType Directory -Path $To -Force | Out-Null
    }

    Get-ChildItem -Path $From -Force | ForEach-Object {
        if ($_.PSIsContainer -and ($ExcludeDirectoryNames -contains $_.Name)) {
            return
        }

        $destination = Join-Path $To $_.Name
        Copy-Item -Path $_.FullName -Destination $destination -Recurse -Force
    }

    Write-Ok "$Label copied/merged"
    return $true
}

function Copy-FileIfExists {
    param(
        [string]$From,
        [string]$To,
        [string]$Label,
        [System.Collections.Generic.List[string]]$Warnings
    )

    if (-not (Test-Path $From)) {
        $Warnings.Add("$Label source file not found: $From")
        return $false
    }

    $destinationDirectory = Split-Path -Path $To -Parent
    if (-not (Test-Path $destinationDirectory)) {
        New-Item -ItemType Directory -Path $destinationDirectory -Force | Out-Null
    }

    Copy-Item -Path $From -Destination $To -Force
    Write-Ok "$Label copied"
    return $true
}

function Read-YamlStringList {
    # Lee una lista YAML de strings bajo una clave dada.
    # Soporta clave de nivel superior (ej. 'commands:') o anidada un
    # nivel (ej. 'overrides:' -> 'agents:'). Parser minimo suficiente
    # para los manifiestos GRM (listas planas de strings). Ver
    # GRM-SCK_Plan_Adaptacion_Instalador_v1 (Opcion A).
    param(
        [string]$Path,
        [string]$TopKey,
        [string]$NestedKey = $null
    )

    if (-not (Test-Path $Path)) { return @() }
    $lines = Get-Content -Path $Path
    $result = [System.Collections.Generic.List[string]]::new()

    $inTop = $false
    $inNested = $false
    $topIndent = -1

    foreach ($raw in $lines) {
        $line = $raw -replace '\t', '    '
        if ($line -match '^\s*#') { continue }
        if ([string]::IsNullOrWhiteSpace($line)) { continue }

        $indent = ($line -replace '^(\s*).*$', '$1').Length
        $trimmed = $line.Trim()

        if (-not $inTop) {
            if ($trimmed -match "^${TopKey}:") {
                $inTop = $true
                $topIndent = $indent
                if (-not $NestedKey) { $inNested = $true }
            }
            continue
        }

        if ($indent -le $topIndent -and $trimmed -notmatch '^-') {
            break
        }

        if ($NestedKey -and -not $inNested) {
            if ($trimmed -match "^${NestedKey}:") { $inNested = $true }
            continue
        }

        if ($trimmed -match '^-\s*(.+)$') {
            $item = $Matches[1].Trim()
            $item = ($item -replace '\s+#.*$', '').Trim()
            $item = $item.Trim('"').Trim("'")
            if ($item) { $result.Add($item) }
        }
    }

    return $result.ToArray()
}

function Copy-ManifestFile {
    # Copia un unico fichero declarado en el manifiesto. Si el origen
    # no existe, la instalacion FALLA (no se degrada). Cumple CA-04.
    param(
        [string]$From,
        [string]$To,
        [string]$Label,
        [System.Collections.Generic.List[string]]$Deployed
    )

    if (-not (Test-Path $From)) {
        throw "Declared artifact not found in Source of Truth: $From ($Label)"
    }

    $destinationDirectory = Split-Path -Path $To -Parent
    if (-not (Test-Path $destinationDirectory)) {
        New-Item -ItemType Directory -Path $destinationDirectory -Force | Out-Null
    }

    Copy-Item -Path $From -Destination $To -Force
    if ($null -ne $Deployed) { $Deployed.Add("$Label|$From|$To") | Out-Null }
    Write-Ok "Deployed $Label"
    return $true
}

function Install-CorporateAgentsAndPrompts {
    # Despliega agentes y prompts corporativos por manifiesto, fichero
    # a fichero. Sustituye la copia por directorio completo (H-INST-01,
    # H-INST-02). Cumple PC-01 y PC-02.
    param(
        [string]$SourceRepoPath,
        [string]$TargetPath,
        [System.Collections.Generic.List[string]]$Deployed
    )

    $extYml = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/extension.yml"
    $preYml = Join-Path $SourceRepoPath "presets/grm-corporate-governance/preset.yml"

    # 1. Comandos corporativos: agent + prompt por cada corp.<cmd>
    $commands = Read-YamlStringList -Path $extYml -TopKey "commands"
    foreach ($cmd in $commands) {
        $agentFrom = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/agents/$cmd.agent.md"
        $agentTo = Join-Path $TargetPath ".github/agents/$cmd.agent.md"
        Copy-ManifestFile -From $agentFrom -To $agentTo -Label "corp agent: $cmd" -Deployed $Deployed | Out-Null

        $promptFrom = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/prompts/$cmd.prompt.md"
        $promptTo = Join-Path $TargetPath ".github/prompts/$cmd.prompt.md"
        Copy-ManifestFile -From $promptFrom -To $promptTo -Label "corp prompt: $cmd" -Deployed $Deployed | Out-Null
    }

    # 2. Overrides de preset: solo agentes (el preset no declara prompts)
    $overrides = Read-YamlStringList -Path $preYml -TopKey "overrides" -NestedKey "agents"
    foreach ($agent in $overrides) {
        $ovrFrom = Join-Path $SourceRepoPath "presets/grm-corporate-governance/agents/$agent"
        $ovrTo = Join-Path $TargetPath ".github/agents/$agent"
        Copy-ManifestFile -From $ovrFrom -To $ovrTo -Label "preset override agent: $agent" -Deployed $Deployed | Out-Null
    }
}

function Read-SkillFrontmatter {
    # Extrae el bloque de frontmatter de un SKILL.md: desde la primera
    # linea, que debe ser exactamente '---', hasta la siguiente linea
    # que sea tambien exactamente '---'. Sin cierre, no hay frontmatter
    # que leer (D-P20-02): el llamador lo trata como fallo de forma.
    #
    # Dentro del bloque, pares clave: valor planos, un nivel, sin
    # anidar. No reutiliza Read-YamlScalar: un frontmatter no tiene
    # TopKey/NestedKey, name y description estan al mismo nivel, y
    # Read-YamlScalar lee el fichero completo sin acotar donde termina
    # el YAML, lo que arriesga capturar texto del cuerpo Markdown.
    #
    # No soporta valores plegados en varias lineas (estilo '>' o '|').
    # El corpus actual no los usa; si aparecen, esta funcion los trata
    # como valor vacio y Assert-SkillShape lo reporta como campo
    # ausente, nunca como exito silencioso.
    param(
        [string]$Path
    )

    $result = @{}
    if (-not (Test-Path $Path)) { return $result }

    $lines = @(Get-Content -Path $Path)
    if ($lines.Count -eq 0 -or $lines[0].Trim() -ne '---') {
        return $result
    }

    $closeIndex = -1
    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -eq '---') {
            $closeIndex = $i
            break
        }
    }
    if ($closeIndex -lt 0) {
        return $result
    }

    for ($i = 1; $i -lt $closeIndex; $i++) {
        $line = $lines[$i]
        if ($line -match '^\s*#') { continue }
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        if ($line -match '^([A-Za-z0-9_]+):\s*(.*)$') {
            $key = $Matches[1]
            $val = $Matches[2].Trim()
            $val = $val.Trim('"').Trim("'")
            $result[$key] = $val
        }
    }

    return $result
}

function Assert-SkillShape {
    # P3 (D-P19-02, D-P20-01b, D-P20-03b, D-P20-04): valida la forma de
    # toda skill desplegable en la Source of Truth, declarada o no en
    # el manifiesto.
    #
    # Se ejecuta sobre el subarbol de origen, antes de copiar nada,
    # igual que la puerta de existencia de Install-CorporateSkills.
    # Ambas puertas conviven: la de existencia cubre las skills
    # declaradas en extension.yml; esta cubre todo directorio de primer
    # nivel que tenga SKILL.md, declarado o no, porque el subarbol
    # completo se despliega igual (D-P19-10).
    #
    # _shared queda fuera sin excepcion explicita: no tiene SKILL.md
    # (D-P19-01), asi que nunca entra en el bucle.
    #
    # Un directorio sin SKILL.md no es un incumplimiento aqui: nadie
    # prometio que fuera una skill. Es criterio de inclusion, no una
    # regla que pueda fallar.
    #
    # Todos los incumplimientos se acumulan y se lanzan juntos, para no
    # obligar a corregir y reinstalar seis veces (mismo patron que la
    # puerta de existencia).
    param(
        [string]$SkillsFrom
    )

    $nameSyntax = '^[a-z0-9]+(-[a-z0-9]+)*$'
    $problems = [System.Collections.Generic.List[string]]::new()

    $skillDirs = @(Get-ChildItem -LiteralPath $SkillsFrom -Directory -Force)
    $validatedDirs = [System.Collections.Generic.List[string]]::new()
    foreach ($dir in $skillDirs) {
        $skillMd = Join-Path $dir.FullName "SKILL.md"
        if (-not (Test-Path $skillMd)) {
            continue
        }
        $validatedDirs.Add($dir.Name) | Out-Null

        $front = Read-SkillFrontmatter -Path $skillMd
        if ($front.Count -eq 0) {
            $problems.Add("$($dir.Name): frontmatter not parseable (missing or unclosed '---' block)") | Out-Null
            continue
        }

        $name = $front['name']
        $description = $front['description']

        if ([string]::IsNullOrWhiteSpace($name)) {
            $problems.Add("$($dir.Name): missing 'name' in frontmatter") | Out-Null
        }
        if ([string]::IsNullOrWhiteSpace($description)) {
            $problems.Add("$($dir.Name): missing 'description' in frontmatter") | Out-Null
        }
        if (-not [string]::IsNullOrWhiteSpace($name)) {
            if ($name -cne $dir.Name) {
                $problems.Add("$($dir.Name): 'name' ('$name') does not match directory name") | Out-Null
            }
            if ($name -cnotmatch $nameSyntax -or $name.Length -gt 64) {
                $problems.Add("$($dir.Name): 'name' ('$name') must be lowercase-with-hyphens, up to 64 characters") | Out-Null
            }
        }
        if (-not [string]::IsNullOrWhiteSpace($description) -and $description.Length -gt 1024) {
            $problems.Add("$($dir.Name): 'description' exceeds 1024 characters ($($description.Length))") | Out-Null
        }
    }

    if ($problems.Count -gt 0) {
        throw "Skill shape validation failed: $($problems -join '; ')"
    }

    # P5b (D-P21-08): en exito, devuelve los directorios de primer nivel
    # que llegaron a tener SKILL.md y pasaron las seis reglas -no todos
    # los de $skillDirs, que incluye tambien _shared-. Esta funcion es
    # la unica que sabe si un directorio tenia forma de skill; el
    # informe no vuelve a preguntarselo a nadie mas.
    return $validatedDirs
}

function Install-CorporateSkills {
    # Despliega el subarbol de skills corporativas en el runtime, que es
    # donde el agente las descubre. Copy-DirectoryMerge ya lleva la
    # extension entera a extensions/, pero .github/skills/ quedaba vacio.
    #
    # El manifiesto es puerta, no inventario (D-P19-10, D-P19-11): toda
    # skill declarada debe existir con su SKILL.md ANTES de copiar nada,
    # y lo que se copia es el subarbol completo, incluidas las carpetas
    # que no se declaran.
    #
    # Segunda puerta, tambien previa a copiar (P3): Assert-SkillShape
    # valida la forma de todo directorio con SKILL.md, declarado o no.
    # Existencia y forma son preguntas distintas y se comprueban por
    # separado; ver Assert-SkillShape para el detalle de las reglas.
    #
    # skills/_shared es una de ellas (D-P19-01). No es una skill, no se
    # declara y no lleva SKILL.md, pero los dos SKILL.md invocan sus
    # scripts por ruta del runtime. Sin el, el primer corp.erase falla.
    #
    # Sin purga (D-P19-12): copia y sobrescribe, nunca borra. Es
    # deliberadamente menos agresiva que resources/tools/Sync-GrmSkills.ps1,
    # que espeja con robocopy /MIR sobre un runtime desechable. Aqui el
    # destino puede contener skills anadidas por el proyecto consumidor,
    # y la politica del instalador es no destruir .github.
    #
    # Una entrada por fichero en $Deployed (D-P19-09), de modo que
    # Assert-DeployedProvenance compara la huella SHA-256 de origen y
    # destino. La verificacion no es nueva: es la que ya cubre agentes y
    # prompts.
    param(
        [string]$SourceRepoPath,
        [string]$TargetPath,
        [System.Collections.Generic.List[string]]$Deployed
    )

    $extYml     = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/extension.yml"
    $skillsFrom = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/skills"

    if (-not (Test-Path $skillsFrom)) {
        throw "Skills subtree not found in Source of Truth: $skillsFrom"
    }

    # 1. Puerta previa sobre el conjunto completo. Falla antes de copiar,
    #    para no dejar el runtime a medio desplegar.
    $skills = @(Read-YamlStringList -Path $extYml -TopKey "skills")
    $missingSkills = [System.Collections.Generic.List[string]]::new()
    foreach ($skill in $skills) {
        $skillDir = Join-Path $skillsFrom $skill
        if (-not (Test-Path $skillDir)) {
            $missingSkills.Add($skill) | Out-Null
            continue
        }
        if (-not (Test-Path (Join-Path $skillDir "SKILL.md"))) {
            $missingSkills.Add("$skill (missing SKILL.md)") | Out-Null
        }
    }
    if ($missingSkills.Count -gt 0) {
        throw "Declared skills not found or incomplete in Source of Truth: $($missingSkills -join ', '). Nothing was copied."
    }

    # 1b. Validacion de forma (P3, D-P20-01b): todo directorio de primer
    #     nivel de la Source of Truth que tenga SKILL.md, declarado o no.
    #     Ver Assert-SkillShape. Tambien corta antes de copiar nada.
    Assert-SkillShape -SkillsFrom $skillsFrom

    # 2. Despliegue del subarbol completo, fichero a fichero.
    #    El prefijo y los ficheros tienen que venir del mismo proveedor.
    #    Resolve-Path conserva la forma corta 8.3 que se le pasa, mientras
    #    que FullName de Get-ChildItem devuelve la forma larga expandida.
    #    Restar longitudes entre las dos formas descuadra la ruta relativa:
    #    medido, C:\Users\SESANC~1\... son 51 caracteres y
    #    C:\Users\sesanchez\... son 52 para el mismo directorio.
    #    La comprobacion de prefijo convierte esa clase de error en un fallo
    #    duro en lugar de en una ruta silenciosamente mal formada.
    $skillsRoot = (Get-Item -LiteralPath $skillsFrom).FullName.TrimEnd('\')
    $prefix     = $skillsRoot + '\'
    $files      = @(Get-ChildItem -LiteralPath $skillsRoot -Recurse -File -Force)
    foreach ($file in $files) {
        if (-not $file.FullName.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
            throw "File outside the skills subtree: $($file.FullName) (expected prefix: $prefix)"
        }
        $relative = $file.FullName.Substring($prefix.Length)
        $skillTo  = Join-Path $TargetPath (".github/skills/" + $relative)
        Copy-ManifestFile -From $file.FullName -To $skillTo -Label "corp skill file: $relative" -Deployed $Deployed | Out-Null
    }

    Write-Ok "Corporate skills deployed: $($skills.Count) declared skill(s), $($files.Count) file(s)"
}

function Get-NativePreservedFiles {
    # Resuelve las rutas de fichero (agent + prompt) para cada clave
    # declarada en native_preserved. Opcion A: agent + prompt.
    param(
        [string]$SourceRepoPath,
        [string]$TargetPath
    )
    $preYml = Join-Path $SourceRepoPath "presets/grm-corporate-governance/preset.yml"
    $keys = Read-YamlStringList -Path $preYml -TopKey "native_preserved"
    $files = [System.Collections.Generic.List[string]]::new()
    foreach ($key in $keys) {
        $files.Add((Join-Path $TargetPath ".github/agents/$key.agent.md"))
        $files.Add((Join-Path $TargetPath ".github/prompts/$key.prompt.md"))
    }
    return $files
}

function Get-FileHashSnapshot {
    # Captura hash SHA256 de una lista de ficheros. Los ausentes se
    # registran como $null (no se fallan: un nativo ausente no es un
    # nativo corrompido).
    param([System.Collections.Generic.List[string]]$Files)
    $snapshot = @{}
    foreach ($f in $Files) {
        if (Test-Path $f) {
            $snapshot[$f] = (Get-FileHash -Path $f -Algorithm SHA256).Hash
        } else {
            $snapshot[$f] = $null
        }
    }
    return $snapshot
}

function Assert-NativePreservedIntact {
    # Compara snapshot antes/despues. Falla si un nativo que existia
    # antes fue modificado o eliminado durante el despliegue corporativo.
    # Cumple PC-03. Devuelve la lista de ficheros verificados intactos.
    param(
        [hashtable]$Before,
        [hashtable]$After
    )
    $verified = [System.Collections.Generic.List[string]]::new()
    foreach ($file in $Before.Keys) {
        $hashBefore = $Before[$file]
        $hashAfter  = $After[$file]

        if ($null -eq $hashBefore) {
            # No existia antes: fuera de alcance de proteccion (tolerancia de version)
            continue
        }
        if ($null -eq $hashAfter) {
            throw "Native preserved artifact was deleted during corporate deployment: $file"
        }
        if ($hashBefore -ne $hashAfter) {
            throw "Native preserved artifact was modified during corporate deployment: $file"
        }
        $verified.Add($file) | Out-Null
    }
    return $verified
}

function Assert-DeployedProvenance {
    # Verifica que cada artefacto desplegado (label|origen|destino)
    # tiene en destino el mismo contenido que su origen en el SoT.
    # Acumula divergencias en la lista Missing (patron existente).
    # Cumple CA-02 / PC-04.
    param(
        [System.Collections.Generic.List[string]]$Deployed,
        [ref]$Missing
    )
    foreach ($entry in $Deployed) {
        $parts = $entry -split '\|', 3
        if ($parts.Count -lt 3) { continue }
        $from = $parts[1]
        $to   = $parts[2]

        if (-not (Test-Path $to)) {
            $Missing.Value += "provenance-missing: $to"
            continue
        }
        if (-not (Test-Path $from)) {
            $Missing.Value += "provenance-source-missing: $from"
            continue
        }
        $hashFrom = (Get-FileHash -Path $from -Algorithm SHA256).Hash
        $hashTo   = (Get-FileHash -Path $to -Algorithm SHA256).Hash
        if ($hashFrom -ne $hashTo) {
            $Missing.Value += "provenance-mismatch: $to"
        }
    }
}

function Assert-DeployedSourcePrefix {
    # P5a (OBS-P2a-01, D-P21-07b): comprueba que el origen de cada
    # artefacto desplegado cuelga de la Source of Truth y que todas las
    # entradas usan una sola forma de la ruta.
    #
    # $SourceRepoPath se normaliza tras el clon con el mismo proveedor
    # que Install-CorporateSkills. Esta funcion es la guarda que lo
    # verifica: si alguien vuelve a introducir un origen de otro
    # proveedor, deja de ser una etiqueta silenciosamente mal formada y
    # pasa a ser un fallo duro. Mismo criterio que la guarda de prefijo
    # de L-11: la guarda importa mas que la correccion.
    #
    # Pregunta distinta de la de Assert-DeployedProvenance, que compara
    # contenido. Se separan por el mismo motivo que D-P20-01 separo
    # existencia de forma: aisladas, se ejercitan con datos sinteticos
    # sin instalar nada (ver resources/tools/Test-InstallationReport.ps1).
    #
    # Acumula en Missing, el canal existente: la instalacion aborta en la
    # validacion de runtime y el informe se genera igualmente desde el
    # finally, con la entrada visible.
    param(
        [System.Collections.Generic.List[string]]$Deployed,
        [string]$SourceRepoPath,
        [ref]$Missing
    )

    # El separador final es deliberado: sin el, un directorio hermano
    # como '...\source-otro' pasaria por estar dentro de '...\source'.
    $prefix = $SourceRepoPath.TrimEnd('\') + '\'

    foreach ($entry in $Deployed) {
        $parts = $entry -split '\|', 3
        if ($parts.Count -lt 3) {
            $Missing.Value += "deployed-entry-malformed: $entry"
            continue
        }
        $from = $parts[1]
        if (-not $from.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
            $Missing.Value += "source-prefix-mismatch: $from"
        }
    }
}

function Get-UndeployedMemoryFiles {
    # Lista ficheros de memory/ presentes en el SoT pero NO declarados
    # en deploys.memory. Informativo (H-INST-07). Devuelve nombres.
    param([string]$SourceRepoPath)

    $memoryDir = Join-Path $SourceRepoPath "presets/grm-corporate-governance/memory"
    if (-not (Test-Path $memoryDir)) { return @() }

    $preYml = Join-Path $SourceRepoPath "presets/grm-corporate-governance/preset.yml"
    # deploys.memory declara pares source/target; extraemos los 'source:'
    $declaredSources = @()
    if (Test-Path $preYml) {
        $inDeploys = $false; $inMemory = $false
        foreach ($raw in (Get-Content $preYml)) {
            $line = $raw -replace '\t','    '
            if ($line -match '^\s*#') { continue }
            $trimmed = $line.Trim()
            if ($trimmed -match '^deploys:') { $inDeploys = $true; continue }
            if ($inDeploys -and $trimmed -match '^memory:') { $inMemory = $true; continue }
            if ($inDeploys -and $line -match '^\S') { $inDeploys = $false; $inMemory = $false }
            if ($inMemory -and $trimmed -match '^-?\s*source:\s*(.+)$') {
                $src = $Matches[1].Trim().Trim('"').Trim("'")
                $declaredSources += (Split-Path -Path $src -Leaf)
            }
        }
    }

    $undeployed = @()
    Get-ChildItem -Path $memoryDir -File | ForEach-Object {
        if ($declaredSources -notcontains $_.Name) {
            $undeployed += "memory/$($_.Name)"
        }
    }
    return $undeployed
}

function Read-YamlScalar {
    # Lee un valor escalar anidado un nivel: TopKey -> NestedKey.
    # Devuelve $null si no existe. Parser minimo (Opcion A, escalares).
    param(
        [string]$Path,
        [string]$TopKey,
        [string]$NestedKey
    )
    if (-not (Test-Path $Path)) { return $null }
    $inTop = $false
    $topIndent = -1
    foreach ($raw in (Get-Content $Path)) {
        $line = $raw -replace '\t', '    '
        if ($line -match '^\s*#') { continue }
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        $indent = ($line -replace '^(\s*).*$', '$1').Length
        $trimmed = $line.Trim()

        if (-not $inTop) {
            if ($trimmed -match "^${TopKey}:") { $inTop = $true; $topIndent = $indent }
            continue
        }
        if ($indent -le $topIndent) { break }
        if ($trimmed -match "^${NestedKey}:\s*(.+)$") {
            $val = $Matches[1].Trim()
            $val = ($val -replace '\s+#.*$', '').Trim()
            $val = $val.Trim('"').Trim("'")
            return $val
        }
    }
    return $null
}

function Assert-SpecKitInstallation {
    # P5 accion 3: verifica que el destino tiene una instalacion de
    # Spec Kit valida (marcada por .specify). Sustituye la precondicion
    # acoplada al runtime heredado (.specify + .github). Cumple H-INST-05.
    param([string]$TargetPath)
    $specifyDir = Join-Path $TargetPath ".specify"
    if (-not (Test-Path $specifyDir)) {
        throw "UpdateExisting requires a valid Spec Kit installation in the target. Missing: $specifyDir. Run 'specify init' first."
    }
}

function Write-SpecKitVersionAdvisory {
    # P5 accion 4: advierte (sin bloquear) si la version de Spec Kit
    # detectada difiere de la validada por GRM. La version validada se
    # declara en extension.yml:compatibility.spec-kit-validated. Si el
    # campo no existe (PA-01 sin decidir), no advierte. Cumple R-02.
    param(
        [string]$SourceRepoPath,
        [string]$DetectedVersion,
        [System.Collections.Generic.List[string]]$Warnings
    )
    $extYml = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/extension.yml"
    $validated = Read-YamlScalar -Path $extYml -TopKey "compatibility" -NestedKey "spec-kit-validated"
    if ([string]::IsNullOrWhiteSpace($validated)) { return }   # PA-01 sin decidir: no se advierte
    if ($validated -eq "current") { return }
    if ($DetectedVersion -notlike "*$validated*") {
        $Warnings.Add("Spec Kit version mismatch: detected '$DetectedVersion', GRM validated '$validated'. Installation proceeds; verify compatibility.") | Out-Null
    }
}

function Invoke-GitChecked {
    param([string[]]$Arguments, [string]$ErrorMessage)
    & git @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw $ErrorMessage
    }
}

function Resolve-TargetWorkspacePolicy {
    param(
        [string]$TargetPath,
        [string]$InstallMode,
        [switch]$Force
    )

    $targetExists = Test-Path $TargetPath

    if ($targetExists -and $InstallMode -eq "FailIfExists") {
        throw "Target directory already exists: $TargetPath. Use -InstallMode CleanInstall -Force to recreate it, or -InstallMode UpdateExisting to update it safely."
    }

    if ($targetExists -and $InstallMode -eq "CleanInstall" -and -not $Force) {
        throw "CleanInstall requires -Force when target directory already exists: $TargetPath"
    }

    if ($targetExists -and $InstallMode -eq "CleanInstall" -and $Force) {
        Remove-Item -Path $TargetPath -Recurse -Force
        New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
        return "CleanInstall"
    }

    if ($targetExists -and $InstallMode -eq "UpdateExisting") {
        Assert-SpecKitInstallation -TargetPath $TargetPath
        return "UpdateExisting"
    }

    if (-not $targetExists) {
        New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
        return "CleanInstall"
    }

    throw "Unsupported target workspace state for path: $TargetPath"
}

function ConvertTo-HashtableRecursive {
    param([object]$InputObject)

    if ($null -eq $InputObject) {
        return $null
    }

    if ($InputObject -is [System.Management.Automation.PSCustomObject]) {
        $hash = [ordered]@{}
        foreach ($property in $InputObject.PSObject.Properties) {
            $hash[$property.Name] = ConvertTo-HashtableRecursive -InputObject $property.Value
        }
        return $hash
    }

    if ($InputObject -is [System.Collections.IEnumerable] -and -not ($InputObject -is [string])) {
        $array = @()
        foreach ($item in $InputObject) {
            $array += ConvertTo-HashtableRecursive -InputObject $item
        }
        return $array
    }

    return $InputObject
}

function Test-JsonContainsToken {
    param(
        [object]$InputObject,
        [string]$Token
    )

    if ($null -eq $InputObject) {
        return $false
    }

    if ($InputObject -is [System.Management.Automation.PSCustomObject]) {
        foreach ($property in $InputObject.PSObject.Properties) {
            if ($property.Name -eq $Token) {
                return $true
            }
            if (Test-JsonContainsToken -InputObject $property.Value -Token $Token) {
                return $true
            }
        }
        return $false
    }

    if ($InputObject -is [System.Collections.IDictionary]) {
        foreach ($key in $InputObject.Keys) {
            if ([string]$key -eq $Token) {
                return $true
            }
            if (Test-JsonContainsToken -InputObject $InputObject[$key] -Token $Token) {
                return $true
            }
        }
        return $false
    }

    if ($InputObject -is [System.Collections.IEnumerable] -and -not ($InputObject -is [string])) {
        foreach ($item in $InputObject) {
            if (Test-JsonContainsToken -InputObject $item -Token $Token) {
                return $true
            }
        }
        return $false
    }

    return ([string]$InputObject -eq $Token)
}

function Merge-WorkflowRegistryObject {
    param(
        [object]$TargetJson,
        [object]$SourceJson
    )

    $targetRegistry = ConvertTo-HashtableRecursive -InputObject $TargetJson
    $sourceRegistry = ConvertTo-HashtableRecursive -InputObject $SourceJson

    if ($null -eq $sourceRegistry) {
        throw "GRM workflow registry source is empty or invalid."
    }

    if ($null -eq $targetRegistry) {
        $targetRegistry = [ordered]@{}
    }

    if (-not ($targetRegistry -is [System.Collections.IDictionary])) {
        throw "Unsupported target workflow registry JSON shape."
    }

    if (-not ($sourceRegistry -is [System.Collections.IDictionary])) {
        throw "Unsupported source workflow registry JSON shape."
    }

    # Shape A: registry as object with top-level workflow ids, for example { "speckit": {...}, "grm": {...} }
    if (-not ($sourceRegistry.Contains("workflows"))) {
        foreach ($key in $sourceRegistry.Keys) {
            $targetRegistry[$key] = $sourceRegistry[$key]
        }
        return $targetRegistry
    }

    # Shape B: Spec Kit registry as { "schema_version": "1.0", "workflows": { "speckit": {...}, "grm": {...} } }
    if ($sourceRegistry.Contains("workflows") -and ($sourceRegistry["workflows"] -is [System.Collections.IDictionary])) {
        if (-not ($targetRegistry.Contains("schema_version")) -and $sourceRegistry.Contains("schema_version")) {
            $targetRegistry["schema_version"] = $sourceRegistry["schema_version"]
        }

        if (-not ($targetRegistry.Contains("workflows")) -or $null -eq $targetRegistry["workflows"]) {
            $targetRegistry["workflows"] = [ordered]@{}
        }

        if (-not ($targetRegistry["workflows"] -is [System.Collections.IDictionary])) {
            throw "Unsupported target workflow registry shape: workflows must be an object."
        }

        foreach ($workflowKey in $sourceRegistry["workflows"].Keys) {
            $targetRegistry["workflows"][$workflowKey] = $sourceRegistry["workflows"][$workflowKey]
        }

        return $targetRegistry
    }

    # Shape C: defensive support for { "workflows": [ { "id": "..." } ] } if future versions change format.
    if ($sourceRegistry.Contains("workflows") -and ($sourceRegistry["workflows"] -is [System.Collections.IEnumerable]) -and -not ($sourceRegistry["workflows"] -is [string])) {
        if (-not ($targetRegistry.Contains("workflows")) -or $null -eq $targetRegistry["workflows"]) {
            $targetRegistry["workflows"] = @()
        }

        $targetWorkflows = @($targetRegistry["workflows"])
        $sourceWorkflows = @($sourceRegistry["workflows"])

        foreach ($sourceWorkflow in $sourceWorkflows) {
            $sourceId = $null
            if ($sourceWorkflow -is [System.Collections.IDictionary]) {
                foreach ($candidateKey in @("id", "name", "key")) {
                    if ($sourceWorkflow.Contains($candidateKey)) {
                        $sourceId = [string]$sourceWorkflow[$candidateKey]
                        break
                    }
                }
            }

            if ([string]::IsNullOrWhiteSpace($sourceId)) {
                $targetWorkflows += $sourceWorkflow
                continue
            }

            $updated = $false
            for ($i = 0; $i -lt $targetWorkflows.Count; $i++) {
                $targetWorkflow = $targetWorkflows[$i]
                if ($targetWorkflow -is [System.Collections.IDictionary]) {
                    foreach ($candidateKey in @("id", "name", "key")) {
                        if ($targetWorkflow.Contains($candidateKey) -and ([string]$targetWorkflow[$candidateKey]) -eq $sourceId) {
                            $targetWorkflows[$i] = $sourceWorkflow
                            $updated = $true
                            break
                        }
                    }
                }
                if ($updated) { break }
            }

            if (-not $updated) {
                $targetWorkflows += $sourceWorkflow
            }
        }

        $targetRegistry["workflows"] = $targetWorkflows
        return $targetRegistry
    }

    throw "Unsupported workflow registry JSON shape."
}

function Install-GrmWorkflows {
    param(
        [string]$SourceRepoPath,
        [string]$TargetPath,
        [System.Collections.Generic.List[string]]$Warnings
    )

    $sourceWorkflowsPath = Join-Path $SourceRepoPath "presets/grm-corporate-governance/workflows"
    $targetWorkflowsPath = Join-Path $TargetPath ".specify/workflows"
    $sourceRegistryPath = Join-Path $sourceWorkflowsPath "workflow-registry.json"
    $targetRegistryPath = Join-Path $targetWorkflowsPath "workflow-registry.json"

    if (-not (Test-Path $sourceWorkflowsPath)) {
        throw "GRM workflows source not found: $sourceWorkflowsPath"
    }

    if (-not (Test-Path $sourceRegistryPath)) {
        throw "GRM workflow registry source not found: $sourceRegistryPath"
    }

    if (-not (Test-Path $targetWorkflowsPath)) {
        New-Item -ItemType Directory -Path $targetWorkflowsPath -Force | Out-Null
    }

    Get-ChildItem -Path $sourceWorkflowsPath -Directory | ForEach-Object {
        $destination = Join-Path $targetWorkflowsPath $_.Name
        Copy-Item -Path $_.FullName -Destination $destination -Recurse -Force
    }

    if (-not (Test-Path $targetRegistryPath)) {
        "{}" | Set-Content -Path $targetRegistryPath -Encoding UTF8
    }

    $sourceJson = Get-Content $sourceRegistryPath -Raw | ConvertFrom-Json
    $targetJson = Get-Content $targetRegistryPath -Raw | ConvertFrom-Json

    $mergedRegistry = Merge-WorkflowRegistryObject -TargetJson $targetJson -SourceJson $sourceJson
    $mergedRegistry | ConvertTo-Json -Depth 30 | Set-Content -Path $targetRegistryPath -Encoding UTF8

    $grmWorkflowPath = Join-Path $targetWorkflowsPath "grm/workflow.yml"
    if (-not (Test-Path $grmWorkflowPath)) {
        throw "GRM workflow was not installed correctly: $grmWorkflowPath"
    }

    $mergedRegistryJson = Get-Content $targetRegistryPath -Raw | ConvertFrom-Json

    if (-not (Test-JsonContainsToken -InputObject $mergedRegistryJson -Token "grm")) {
        throw "GRM workflow registry entry was not merged correctly."
    }

    if (-not (Test-JsonContainsToken -InputObject $mergedRegistryJson -Token "speckit")) {
        throw "Native speckit workflow registry entry is missing after merge."
    }

    $detectedWorkflowEntries = @()
    if ($mergedRegistryJson.PSObject.Properties.Name -contains "workflows") {
        $workflowNode = $mergedRegistryJson.workflows
        if ($workflowNode -is [System.Management.Automation.PSCustomObject]) {
            $detectedWorkflowEntries = @($workflowNode.PSObject.Properties.Name)
        }
        elseif ($workflowNode -is [System.Collections.IEnumerable] -and -not ($workflowNode -is [string])) {
            foreach ($workflow in @($workflowNode)) {
                if ($workflow.PSObject.Properties.Name -contains "id") { $detectedWorkflowEntries += [string]$workflow.id }
                elseif ($workflow.PSObject.Properties.Name -contains "name") { $detectedWorkflowEntries += [string]$workflow.name }
                elseif ($workflow.PSObject.Properties.Name -contains "key") { $detectedWorkflowEntries += [string]$workflow.key }
            }
        }
    }
    else {
        $detectedWorkflowEntries = @($mergedRegistryJson.PSObject.Properties.Name)
    }

    Write-Ok "GRM workflows installed and workflow registry merged"
    return $detectedWorkflowEntries
}

function New-InstallationReport {
    param(
        [string]$ReportPath,
        [string]$Status,
        [string]$ErrorMessage,
        [datetime]$StartTime,
        [datetime]$EndTime,
        [string]$RootPath,
        [string]$TargetPath,
        [string]$InstallMode,
        [string]$EffectiveMode,
        [string]$GitVersion,
        [string]$SpecKitVersion,
        [string]$SpecKitInitCommandForReport,
        [string]$InstalledRemote,
        [string]$InstalledBranch,
        [string]$InstalledCommit,
        [string]$SourceRepoPath,
        [bool]$KeepSourceCache,
        [string[]]$AgentFiles,
        [string[]]$PromptFiles,
        [string[]]$WorkflowEntries,
        [bool]$SamplesCopied,
        [bool]$DocsCopied,
        [bool]$ConstitutionCopied,
        [bool]$BacklogCatalogCopied,
        [string[]]$Missing,
        [string[]]$DeployedArtifacts,
        [string[]]$PreservedArtifacts,
        [string[]]$UndeployedArtifacts,
        [bool]$SkillsShapeValidated,
        [string[]]$ValidatedSkillDirs,
        [System.Collections.Generic.List[string]]$Warnings
    )

    $reportDirectory = Split-Path -Path $ReportPath -Parent
    if (-not [string]::IsNullOrWhiteSpace($reportDirectory) -and -not (Test-Path $reportDirectory)) {
        New-Item -ItemType Directory -Path $reportDirectory -Force | Out-Null
    }

    $agentLines = if ($AgentFiles.Count -gt 0) { ($AgentFiles | Sort-Object | ForEach-Object { "- $_" }) -join "`n" } else { "- none detected" }
    $promptLines = if ($PromptFiles.Count -gt 0) { ($PromptFiles | Sort-Object | ForEach-Object { "- $_" }) -join "`n" } else { "- none detected" }

    # P5b (D-P21-01c, D-P21-03a, D-P21-04): la subseccion de skills no
    # sale de una unica fuente. Assert-SkillShape es quien conoce la
    # forma -devuelve, via Install-CorporateSkills sin cambiar su
    # contrato, los directorios que pasaron la validacion-, y el
    # recuento de ficheros por directorio se deriva de DeployedArtifacts,
    # que ya es la fuente de verdad de procedencia (la misma lista que
    # alimenta Assert-DeployedProvenance). _shared aparece aqui porque
    # tambien despliega ficheros con la etiqueta "corp skill file:",
    # pero nunca entra en ValidatedSkillDirs por no tener SKILL.md: se
    # distingue, no se omite, para no contradecir el recuento de
    # Deployed Corporate Artifacts.
    $skillFileGroups = [ordered]@{}
    foreach ($entry in $DeployedArtifacts) {
        $entryParts = $entry -split '\|', 3
        if ($entryParts.Count -lt 1) { continue }
        $entryLabel = $entryParts[0]
        if (-not $entryLabel.StartsWith("corp skill file: ")) { continue }
        $skillRelative = $entryLabel.Substring("corp skill file: ".Length)
        $skillTopDir = ($skillRelative -split '[\\/]')[0]
        if (-not $skillFileGroups.Contains($skillTopDir)) { $skillFileGroups[$skillTopDir] = 0 }
        $skillFileGroups[$skillTopDir] = $skillFileGroups[$skillTopDir] + 1
    }

    if (-not $SkillsShapeValidated) {
        # Estado 3 (D-P21-04): la ejecucion nunca llego a este paso.
        # Distinto de "sin skills": aqui no se sabe si las habria habido.
        $skillLines = "- shape validation not executed: installation stopped before this step"
    }
    elseif ($skillFileGroups.Count -eq 0) {
        # Estado 2 (D-P21-04): la validacion corrio y no encontro ningun
        # directorio de skill, declarado o no, en la Source of Truth.
        $skillLines = "- shape validated: no skill directories found in the Source of Truth"
    }
    else {
        # Estado 1 (D-P21-04): validadas y desplegadas. Una linea por
        # directorio, ordenada por nombre para que el informe sea
        # reproducible byte a byte entre ejecuciones con el mismo payload.
        $skillLines = ($skillFileGroups.Keys | Sort-Object | ForEach-Object {
            $skillDirName = $_
            $skillFileCount = $skillFileGroups[$skillDirName]
            $skillFileWord = if ($skillFileCount -eq 1) { "file" } else { "files" }
            if ($ValidatedSkillDirs -contains $skillDirName) {
                "- ${skillDirName}: $skillFileCount $skillFileWord, shape validated"
            } else {
                "- ${skillDirName}: $skillFileCount $skillFileWord, not a skill (no SKILL.md)"
            }
        }) -join "`n"
    }

    $workflowLines = if ($WorkflowEntries.Count -gt 0) { ($WorkflowEntries | Sort-Object | ForEach-Object { "- $_" }) -join "`n" } else { "- none detected" }
    $missingLines = if ($Missing.Count -gt 0) { ($Missing | ForEach-Object { "- $_" }) -join "`n" } else { "- none" }
    $warningLines = if ($Warnings.Count -gt 0) { ($Warnings | ForEach-Object { "- $_" }) -join "`n" } else { "- none" }
    $deployedLines = if ($DeployedArtifacts.Count -gt 0) { ($DeployedArtifacts | Sort-Object | ForEach-Object { $p = $_ -split '\|', 3; "- $($p[0]): ``$($p[1])`` -> ``$($p[2])``" }) -join "`n" } else { "- none" }
    $preservedLines = if ($PreservedArtifacts.Count -gt 0) { ($PreservedArtifacts | Sort-Object | ForEach-Object { "- $_" }) -join "`n" } else { "- none" }
    $undeployedLines = if ($UndeployedArtifacts.Count -gt 0) { ($UndeployedArtifacts | Sort-Object | ForEach-Object { "- $_" }) -join "`n" } else { "- none" }
    $errorBlock = if ([string]::IsNullOrWhiteSpace($ErrorMessage)) { "- none" } else { "- $ErrorMessage" }

    $content = @"
# GRM Custom Spec Kit Installation Report

## Status

$Status

## Execution

| Field | Value |
|---|---|
| Started | $StartTime |
| Finished | $EndTime |
| Root | $RootPath |
| Target | $TargetPath |
| Requested install mode | $InstallMode |
| Effective install mode | $EffectiveMode |
| Git | $GitVersion |
| Spec Kit (detected) | $SpecKitVersion |
| Spec Kit init command | $SpecKitInitCommandForReport |

## GRM Customization Source

| Field | Value |
|---|---|
| Repository | $InstalledRemote |
| Branch | $InstalledBranch |
| Commit | $InstalledCommit |
| Cache path | $SourceRepoPath |
| Cache retained | $KeepSourceCache |

## Installed Runtime

### Agents

$agentLines

### Prompts

$promptLines

### Skills

$skillLines

### Workflows

$workflowLines

## Deployed Corporate Artifacts

$deployedLines

## Preserved Native Artifacts

Verified intact under Spec Kit (detected): $SpecKitVersion

$preservedLines

## Not Deployed (present in Source of Truth, not declared)

$undeployedLines

## Supporting Assets

| Asset | Copied |
|---|---|
| samples | $SamplesCopied |
| docs | $DocsCopied |
| constitution | $ConstitutionCopied |
| backlog catalogue template | $BacklogCatalogCopied |

## Missing Items

$missingLines

## Warnings

$warningLines

## Error Details

$errorBlock
"@

    Set-Content -Path $ReportPath -Value $content -Encoding UTF8
}

if ([string]::IsNullOrWhiteSpace($TargetName)) {
    $TargetName = Read-Host "Nombre del nuevo directorio E2E"
}

if ([string]::IsNullOrWhiteSpace($TargetName)) {
    throw "TargetName is required. Example: .\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01"
}

if ($TargetName -match '[\\/:*?"<>|]') {
    throw "TargetName contains invalid path characters: $TargetName"
}

$StartTime = Get-Date
$Warnings = [System.Collections.Generic.List[string]]::new()
$Missing = @()
$AgentFiles = @()
$PromptFiles = @()
$DeployedArtifacts = [System.Collections.Generic.List[string]]::new()
$PreservedArtifacts = @()
$UndeployedArtifacts = @()
$WorkflowEntries = @()
$SkillsShapeValidated = $false
$ValidatedSkillDirs = @()
$SamplesCopied = $false
$DocsCopied = $false
$ConstitutionCopied = $false
$BacklogCatalogCopied = $false
$GitVersion = "unknown"
$SpecKitVersion = "unknown"
$SpecKitInitCommandForReport = "specify init --here --integration $Integration --script $ScriptType --force"
$CacheRoot = Join-Path $env:TEMP "grm-custom-spec-kit-cache"
$InstalledCommit = "unknown"
$InstalledRemote = $SourceRepoUrl
$InstalledBranch = $Branch
$SourceRepoPath = "unknown"
$TargetPath = "unknown"
$RootPath = "unknown"
$EffectiveMode = "not-started"
$ReportPath = "unknown"
$Status = "FAILED"
$CapturedErrorMessage = ""

try {
    Write-Step "Pre-flight checks"
    Assert-Command git
    Assert-Command specify

    $RootPath = (New-Item -ItemType Directory -Path $Root -Force).FullName
    $TargetPath = Join-Path $RootPath $TargetName
    $ReportPath = Join-Path $TargetPath "installation-report.md"
    $GitVersion = Get-CommandVersionSafe -CommandName git -Arguments @("--version")
    $SpecKitVersion = Get-CommandVersionSafe -CommandName specify -Arguments @("--version")

    Write-Ok "Pre-flight checks passed"

    Write-Step "Resolve target workspace policy"
    $EffectiveMode = Resolve-TargetWorkspacePolicy -TargetPath $TargetPath -InstallMode $InstallMode -Force:$Force
    Write-Ok "Effective install mode: $EffectiveMode"

    Write-Step "Prepare GRM customization source"
    if (Test-Path $CacheRoot) {
        Remove-Item -Path $CacheRoot -Recurse -Force
    }
    New-Item -ItemType Directory -Path $CacheRoot -Force | Out-Null
    $SourceRepoPath = Join-Path $CacheRoot "source"

    Invoke-GitChecked -Arguments @("clone", "--branch", $Branch, "--single-branch", $SourceRepoUrl, $SourceRepoPath) -ErrorMessage "Unable to clone GRM customization repository."

    # P5a (OBS-P2a-01): $env:TEMP puede venir en forma corta 8.3
    # (C:\Users\SESANC~1\...). Todo lo derivado de $CacheRoot con
    # Join-Path hereda esa forma, mientras que el FullName que devuelve
    # Get-ChildItem en Install-CorporateSkills es la forma larga. Las dos
    # convivian en la misma lista de artefactos y el informe las imprimia
    # mezcladas.
    #
    # Se normaliza una sola vez, aqui, con el MISMO proveedor que usa
    # Install-CorporateSkills para calcular su prefijo. Lo que hace
    # correcta la correccion no es que Get-Item expanda el 8.3, sino que
    # ambos lados obtienen la ruta de la misma forma: coinciden por
    # construccion, no por coincidencia.
    #
    # No puede hacerse en la asignacion de $SourceRepoPath: el directorio
    # no existe hasta que el clon termina.
    $SourceRepoPath = (Get-Item -LiteralPath $SourceRepoPath).FullName.TrimEnd('\')

    Push-Location $SourceRepoPath
    try {
        $InstalledCommit = (& git rev-parse HEAD).Trim()
    }
    finally {
        Pop-Location
    }
    Write-Ok "GRM customization source cloned"

    if ($EffectiveMode -eq "CleanInstall") {
        Write-Step "Initialize Spec Kit runtime"
        Push-Location $TargetPath
        try {
            & specify init --here --integration $Integration --script $ScriptType --force
            if ($LASTEXITCODE -ne 0) {
                throw "Spec Kit initialization failed."
            }
        }
        finally {
            Pop-Location
        }
        Write-Ok "Spec Kit initialized with integration=$Integration and script=$ScriptType"

        if (-not $SkipGitInit) {
            Write-Step "Initialize Git repository"
            Push-Location $TargetPath
            try {
                if (-not (Test-Path (Join-Path $TargetPath ".git"))) {
                    Invoke-GitChecked -Arguments @("init") -ErrorMessage "Unable to initialize Git repository."
                }
                if ($CreateBranch) {
                    Invoke-GitChecked -Arguments @("checkout", "-B", $BranchName) -ErrorMessage "Unable to create or switch Git branch."
                }
            }
            finally {
                Pop-Location
            }
            Write-Ok "Git repository initialized"
        }
    }
    else {
        Write-Step "Update existing workspace"
        Write-SpecKitVersionAdvisory -SourceRepoPath $SourceRepoPath -DetectedVersion $SpecKitVersion -Warnings $Warnings
        Write-Ok "Existing runtime preserved. Spec Kit init was not executed."
    }

    Write-Step "Apply GRM source-of-truth assets"
    $extensionFrom = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow"
    $extensionTo = Join-Path $TargetPath "extensions/grm-corporate-workflow"
    Copy-DirectoryMerge -From $extensionFrom -To $extensionTo -Label "GRM corporate workflow extension" -Warnings $Warnings | Out-Null

    $presetFrom = Join-Path $SourceRepoPath "presets/grm-corporate-governance"
    $presetTo = Join-Path $TargetPath "presets/grm-corporate-governance"
    Copy-DirectoryMerge -From $presetFrom -To $presetTo -Label "GRM corporate governance preset" -Warnings $Warnings | Out-Null

    Write-Step "Capture native preserved snapshot"
    $NativePreservedFiles = Get-NativePreservedFiles -SourceRepoPath $SourceRepoPath -TargetPath $TargetPath
    $NativeHashBefore = Get-FileHashSnapshot -Files $NativePreservedFiles

    Write-Step "Deploy corporate agents and prompts (manifest-driven)"
    $agentsTo = Join-Path $TargetPath ".github/agents"
    $promptsTo = Join-Path $TargetPath ".github/prompts"
    Install-CorporateAgentsAndPrompts -SourceRepoPath $SourceRepoPath -TargetPath $TargetPath -Deployed $DeployedArtifacts

    Write-Step "Deploy corporate skills (manifest-gated, full subtree)"
    # P5b: Install-CorporateSkills no cambia su contrato (D-P21-01c). Lo
    # que cambia es que ya no se descarta su salida: Assert-SkillShape
    # (linea sin Out-Null en su invocacion) devuelve ahora los
    # directorios que pasaron la validacion, y esa devolucion atraviesa
    # Install-CorporateSkills sin tocar su cuerpo, porque ninguna otra
    # instruccion de la funcion deja nada mas sin suprimir en la
    # pipeline: las demas ya usan Out-Null o asignacion.
    $ValidatedSkillDirs = @(Install-CorporateSkills -SourceRepoPath $SourceRepoPath -TargetPath $TargetPath -Deployed $DeployedArtifacts)
    $SkillsShapeValidated = $true

    Write-Step "Verify native preserved artifacts are intact"
    $NativeHashAfter = Get-FileHashSnapshot -Files $NativePreservedFiles
    $PreservedArtifacts = @(Assert-NativePreservedIntact -Before $NativeHashBefore -After $NativeHashAfter)
    Write-Ok "Native preserved artifacts verified intact: $($PreservedArtifacts.Count) file(s)"

    Write-Step "Install GRM workflows"
    $WorkflowEntries = @(Install-GrmWorkflows -SourceRepoPath $SourceRepoPath -TargetPath $TargetPath -Warnings $Warnings)

    Write-Step "Copy supporting assets"
    $SamplesCopied = Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "samples") -To (Join-Path $TargetPath "samples") -Label "GRM samples" -Warnings $Warnings
    $DocsCopied = Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "docs") -To (Join-Path $TargetPath "docs") -Label "GRM docs" -Warnings $Warnings -ExcludeDirectoryNames @("sessions")

    $constitutionSource = Join-Path $SourceRepoPath "presets/grm-corporate-governance/memory/constitution.md"
    $constitutionTarget = Join-Path $TargetPath ".specify/memory/constitution.md"
    $ConstitutionCopied = Copy-FileIfExists -From $constitutionSource -To $constitutionTarget -Label "GRM corporate constitution" -Warnings $Warnings

    # P4: plantilla de catalogo de backlog. Solo el ejemplo se copia, y
    # se sobrescribe siempre (D-P20-07): es nuestra plantilla, no
    # configuracion del consumidor. grm-backlog.yml (sin sufijo) nunca
    # se toca desde aqui, asi que no hay riesgo de pisar la
    # configuracion real del proyecto consumidor.
    $backlogCatalogSource = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/config/grm-backlog.example.yml"
    $backlogCatalogTarget = Join-Path $TargetPath ".specify/grm-backlog.example.yml"
    $BacklogCatalogCopied = Copy-FileIfExists -From $backlogCatalogSource -To $backlogCatalogTarget -Label "GRM backlog catalogue template" -Warnings $Warnings

    Write-Step "Validate installed runtime"
    $requiredPaths = @(
        ".github/agents",
        ".github/prompts",
        ".specify",
        ".specify/workflows",
        ".specify/workflows/speckit/workflow.yml",
        ".specify/workflows/grm/workflow.yml",
        ".specify/workflows/workflow-registry.json",
        "extensions/grm-corporate-workflow",
        "presets/grm-corporate-governance"
    )

    foreach ($relativePath in $requiredPaths) {
        $fullPath = Join-Path $TargetPath $relativePath
        if (-not (Test-Path $fullPath)) {
            $Missing += $relativePath
        }
    }

    $registryPath = Join-Path $TargetPath ".specify/workflows/workflow-registry.json"
    if (Test-Path $registryPath) {
        $registry = Get-Content $registryPath -Raw | ConvertFrom-Json
        if (-not (Test-JsonContainsToken -InputObject $registry -Token "speckit")) {
            $Missing += ".specify/workflows/workflow-registry.json:speckit"
        }
        if (-not (Test-JsonContainsToken -InputObject $registry -Token "grm")) {
            $Missing += ".specify/workflows/workflow-registry.json:grm"
        }
    }

    Assert-DeployedProvenance -Deployed $DeployedArtifacts -Missing ([ref]$Missing)
    Assert-DeployedSourcePrefix -Deployed $DeployedArtifacts -SourceRepoPath $SourceRepoPath -Missing ([ref]$Missing)
    $UndeployedArtifacts = @(Get-UndeployedMemoryFiles -SourceRepoPath $SourceRepoPath)

    if (Test-Path $agentsTo) {
        $AgentFiles = @(Get-ChildItem -Path $agentsTo -File | Select-Object -ExpandProperty Name)
    }
    if (Test-Path $promptsTo) {
        $PromptFiles = @(Get-ChildItem -Path $promptsTo -File | Select-Object -ExpandProperty Name)
    }

    if ($Missing.Count -gt 0) {
        throw "Runtime validation failed. Missing items: $($Missing -join ', ')"
    }

    Write-Ok "Runtime validation passed"
    $Status = "SUCCESS"
}
catch {
    $CapturedErrorMessage = $_.Exception.Message
    Write-Host "`n[ERROR] Bootstrap failed: $CapturedErrorMessage" -ForegroundColor Red
    $Status = "FAILED"
}
finally {
    $EndTime = Get-Date

    if ($TargetPath -ne "unknown") {
        if ($ReportPath -eq "unknown") {
            $ReportPath = Join-Path $TargetPath "installation-report.md"
        }

        try {
            New-InstallationReport `
                -ReportPath $ReportPath `
                -Status $Status `
                -ErrorMessage $CapturedErrorMessage `
                -StartTime $StartTime `
                -EndTime $EndTime `
                -RootPath $RootPath `
                -TargetPath $TargetPath `
                -InstallMode $InstallMode `
                -EffectiveMode $EffectiveMode `
                -GitVersion $GitVersion `
                -SpecKitVersion $SpecKitVersion `
                -SpecKitInitCommandForReport $SpecKitInitCommandForReport `
                -InstalledRemote $InstalledRemote `
                -InstalledBranch $InstalledBranch `
                -InstalledCommit $InstalledCommit `
                -SourceRepoPath $SourceRepoPath `
                -KeepSourceCache:$KeepSourceCache `
                -AgentFiles $AgentFiles `
                -PromptFiles $PromptFiles `
                -WorkflowEntries $WorkflowEntries `
                -SamplesCopied:$SamplesCopied `
                -DocsCopied:$DocsCopied `
                -ConstitutionCopied:$ConstitutionCopied `
                -BacklogCatalogCopied:$BacklogCatalogCopied `
                -Missing $Missing `
                -DeployedArtifacts $DeployedArtifacts `
                -PreservedArtifacts $PreservedArtifacts `
                -UndeployedArtifacts $UndeployedArtifacts `
                -SkillsShapeValidated:$SkillsShapeValidated `
                -ValidatedSkillDirs $ValidatedSkillDirs `
                -Warnings $Warnings
            Write-Ok "Installation report generated: $ReportPath"
        }
        catch {
            Write-Warn2 "Could not generate installation report: $($_.Exception.Message)"
        }
    }

    if (-not $KeepSourceCache -and (Test-Path $CacheRoot)) {
        try {
            Remove-Item -Path $CacheRoot -Recurse -Force
        }
        catch {
            Write-Warn2 "Could not remove source cache: $CacheRoot"
        }
    }
}

if ($Status -ne "SUCCESS") {
    exit 1
}

Write-Ok "Bootstrap completed"
exit 0
