<#
.SYNOPSIS
Bootstrap or update a GRM Custom Spec Kit workspace.

.DESCRIPTION
Creates or updates a validation workspace for GRM Custom Spec Kit.

Supported modes:
- FailIfExists: safe default. Fails when target directory already exists.
- CleanInstall: creates a clean workspace. If target exists, requires -Force and deletes it.
- UpdateExisting: updates an existing workspace non-destructively. Does not run specify init by default.

Deterministic Spec Kit initialization for CleanInstall:
- specify init --here --integration copilot --script ps --force

Runtime merge policy:
- Does NOT delete .github or .specify generated by Spec Kit, except during an explicit CleanInstall -Force.
- Copies GRM source-of-truth assets into the target.
- Merges runtime files over the clean or existing runtime where names match.
- Preserves additional standard Spec Kit runtime files introduced by the installed version.
- Installs corporate workflows from presets/grm-corporate-governance/workflows into .specify/workflows.
- Merges workflow-registry.json additively, preserving native entries such as speckit.
- Generates installation-report.md in both successful and failed executions.

.EXAMPLES
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01 -InstallMode CleanInstall -Force
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01 -InstallMode UpdateExisting
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01 -Branch main -KeepSourceCache
#>

[CmdletBinding()]
param(
    [string]$Root = "C:\dev\proys",
    [string]$TargetName,
    [string]$SourceRepoUrl = "https://github.com/sesanchezromeu/grm-custom-spec-kit.git",
    [string]$Branch = "main",
    [string]$Integration = "copilot",
    [string]$ScriptType = "ps",
    [ValidateSet("FailIfExists", "CleanInstall", "UpdateExisting")]
    [string]$InstallMode = "FailIfExists",
    [switch]$Force,
    [switch]$KeepSourceCache,
    [switch]$SkipGitInit,
    [switch]$CreateBranch,
    [string]$BranchName = "chore/e2e-clean-install"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([string]$Message)
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Write-Warn2 {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Assert-Command {
    param([string]$CommandName)
    if (-not (Get-Command $CommandName -ErrorAction SilentlyContinue)) {
        throw "Required command not found in PATH: $CommandName"
    }
}

function Get-CommandVersionSafe {
    param([string]$CommandName, [string[]]$Arguments)
    try {
        $output = & $CommandName @Arguments 2>&1 | Select-Object -First 1
        if ([string]::IsNullOrWhiteSpace(($output | Out-String))) {
            return "unknown"
        }
        return ($output | Out-String).Trim()
    }
    catch {
        return "unknown"
    }
}

function Copy-DirectoryMerge {
    param(
        [string]$From,
        [string]$To,
        [string]$Label,
        [System.Collections.Generic.List[string]]$Warnings,
        [string[]]$ExcludeDirectoryNames = @()
    )

    if (-not (Test-Path $From)) {
        $Warnings.Add("$Label source not found: $From")
        return $false
    }

    if (-not (Test-Path $To)) {
        New-Item -ItemType Directory -Path $To -Force | Out-Null
    }

    Get-ChildItem -Path $From -Force | ForEach-Object {
        if ($_.PSIsContainer -and ($ExcludeDirectoryNames -contains $_.Name)) {
            return
        }

        $destination = Join-Path $To $_.Name
        Copy-Item -Path $_.FullName -Destination $destination -Recurse -Force
    }

    Write-Ok "$Label copied/merged"
    return $true
}

function Copy-FileIfExists {
    param(
        [string]$From,
        [string]$To,
        [string]$Label,
        [System.Collections.Generic.List[string]]$Warnings
    )

    if (-not (Test-Path $From)) {
        $Warnings.Add("$Label source file not found: $From")
        return $false
    }

    $destinationDirectory = Split-Path -Path $To -Parent
    if (-not (Test-Path $destinationDirectory)) {
        New-Item -ItemType Directory -Path $destinationDirectory -Force | Out-Null
    }

    Copy-Item -Path $From -Destination $To -Force
    Write-Ok "$Label copied"
    return $true
}

function Read-YamlStringList {
    # Lee una lista YAML de strings bajo una clave dada.
    # Soporta clave de nivel superior (ej. 'commands:') o anidada un
    # nivel (ej. 'overrides:' -> 'agents:'). Parser minimo suficiente
    # para los manifiestos GRM (listas planas de strings). Ver
    # GRM-SCK_Plan_Adaptacion_Instalador_v1 (Opcion A).
    param(
        [string]$Path,
        [string]$TopKey,
        [string]$NestedKey = $null
    )

    if (-not (Test-Path $Path)) { return @() }
    $lines = Get-Content -Path $Path
    $result = [System.Collections.Generic.List[string]]::new()

    $inTop = $false
    $inNested = $false
    $topIndent = -1

    foreach ($raw in $lines) {
        $line = $raw -replace '\t', '    '
        if ($line -match '^\s*#') { continue }
        if ([string]::IsNullOrWhiteSpace($line)) { continue }

        $indent = ($line -replace '^(\s*).*$', '$1').Length
        $trimmed = $line.Trim()

        if (-not $inTop) {
            if ($trimmed -match "^${TopKey}:") {
                $inTop = $true
                $topIndent = $indent
                if (-not $NestedKey) { $inNested = $true }
            }
            continue
        }

        if ($indent -le $topIndent -and $trimmed -notmatch '^-') {
            break
        }

        if ($NestedKey -and -not $inNested) {
            if ($trimmed -match "^${NestedKey}:") { $inNested = $true }
            continue
        }

        if ($trimmed -match '^-\s*(.+)$') {
            $item = $Matches[1].Trim()
            $item = ($item -replace '\s+#.*$', '').Trim()
            $item = $item.Trim('"').Trim("'")
            if ($item) { $result.Add($item) }
        }
    }

    return $result.ToArray()
}

function Copy-ManifestFile {
    # Copia un unico fichero declarado en el manifiesto. Si el origen
    # no existe, la instalacion FALLA (no se degrada). Cumple CA-04.
    param(
        [string]$From,
        [string]$To,
        [string]$Label,
        [System.Collections.Generic.List[string]]$Deployed
    )

    if (-not (Test-Path $From)) {
        throw "Declared artifact not found in Source of Truth: $From ($Label)"
    }

    $destinationDirectory = Split-Path -Path $To -Parent
    if (-not (Test-Path $destinationDirectory)) {
        New-Item -ItemType Directory -Path $destinationDirectory -Force | Out-Null
    }

    Copy-Item -Path $From -Destination $To -Force
    if ($Deployed) { $Deployed.Add("$Label|$From|$To") | Out-Null }
    Write-Ok "Deployed $Label"
    return $true
}

function Install-CorporateAgentsAndPrompts {
    # Despliega agentes y prompts corporativos por manifiesto, fichero
    # a fichero. Sustituye la copia por directorio completo (H-INST-01,
    # H-INST-02). Cumple PC-01 y PC-02.
    param(
        [string]$SourceRepoPath,
        [string]$TargetPath,
        [System.Collections.Generic.List[string]]$Deployed
    )

    $extYml = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/extension.yml"
    $preYml = Join-Path $SourceRepoPath "presets/grm-corporate-governance/preset.yml"

    # 1. Comandos corporativos: agent + prompt por cada corp.<cmd>
    $commands = Read-YamlStringList -Path $extYml -TopKey "commands"
    foreach ($cmd in $commands) {
        $agentFrom = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/agents/$cmd.agent.md"
        $agentTo = Join-Path $TargetPath ".github/agents/$cmd.agent.md"
        Copy-ManifestFile -From $agentFrom -To $agentTo -Label "corp agent: $cmd" -Deployed $Deployed | Out-Null

        $promptFrom = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow/prompts/$cmd.prompt.md"
        $promptTo = Join-Path $TargetPath ".github/prompts/$cmd.prompt.md"
        Copy-ManifestFile -From $promptFrom -To $promptTo -Label "corp prompt: $cmd" -Deployed $Deployed | Out-Null
    }

    # 2. Overrides de preset: solo agentes (el preset no declara prompts)
    $overrides = Read-YamlStringList -Path $preYml -TopKey "overrides" -NestedKey "agents"
    foreach ($agent in $overrides) {
        $ovrFrom = Join-Path $SourceRepoPath "presets/grm-corporate-governance/agents/$agent"
        $ovrTo = Join-Path $TargetPath ".github/agents/$agent"
        Copy-ManifestFile -From $ovrFrom -To $ovrTo -Label "preset override agent: $agent" -Deployed $Deployed | Out-Null
    }
}

function Invoke-GitChecked {
    param([string[]]$Arguments, [string]$ErrorMessage)
    & git @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw $ErrorMessage
    }
}

function Resolve-TargetWorkspacePolicy {
    param(
        [string]$TargetPath,
        [string]$InstallMode,
        [switch]$Force
    )

    $targetExists = Test-Path $TargetPath

    if ($targetExists -and $InstallMode -eq "FailIfExists") {
        throw "Target directory already exists: $TargetPath. Use -InstallMode CleanInstall -Force to recreate it, or -InstallMode UpdateExisting to update it safely."
    }

    if ($targetExists -and $InstallMode -eq "CleanInstall" -and -not $Force) {
        throw "CleanInstall requires -Force when target directory already exists: $TargetPath"
    }

    if ($targetExists -and $InstallMode -eq "CleanInstall" -and $Force) {
        Remove-Item -Path $TargetPath -Recurse -Force
        New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
        return "CleanInstall"
    }

    if ($targetExists -and $InstallMode -eq "UpdateExisting") {
        if (-not (Test-Path (Join-Path $TargetPath ".specify"))) {
            throw "UpdateExisting requires an existing Spec Kit runtime directory: $TargetPath\.specify"
        }
        if (-not (Test-Path (Join-Path $TargetPath ".github"))) {
            throw "UpdateExisting requires an existing Copilot runtime directory: $TargetPath\.github"
        }
        return "UpdateExisting"
    }

    if (-not $targetExists) {
        New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
        return "CleanInstall"
    }

    throw "Unsupported target workspace state for path: $TargetPath"
}

function ConvertTo-HashtableRecursive {
    param([object]$InputObject)

    if ($null -eq $InputObject) {
        return $null
    }

    if ($InputObject -is [System.Management.Automation.PSCustomObject]) {
        $hash = [ordered]@{}
        foreach ($property in $InputObject.PSObject.Properties) {
            $hash[$property.Name] = ConvertTo-HashtableRecursive -InputObject $property.Value
        }
        return $hash
    }

    if ($InputObject -is [System.Collections.IEnumerable] -and -not ($InputObject -is [string])) {
        $array = @()
        foreach ($item in $InputObject) {
            $array += ConvertTo-HashtableRecursive -InputObject $item
        }
        return $array
    }

    return $InputObject
}

function Test-JsonContainsToken {
    param(
        [object]$InputObject,
        [string]$Token
    )

    if ($null -eq $InputObject) {
        return $false
    }

    if ($InputObject -is [System.Management.Automation.PSCustomObject]) {
        foreach ($property in $InputObject.PSObject.Properties) {
            if ($property.Name -eq $Token) {
                return $true
            }
            if (Test-JsonContainsToken -InputObject $property.Value -Token $Token) {
                return $true
            }
        }
        return $false
    }

    if ($InputObject -is [System.Collections.IDictionary]) {
        foreach ($key in $InputObject.Keys) {
            if ([string]$key -eq $Token) {
                return $true
            }
            if (Test-JsonContainsToken -InputObject $InputObject[$key] -Token $Token) {
                return $true
            }
        }
        return $false
    }

    if ($InputObject -is [System.Collections.IEnumerable] -and -not ($InputObject -is [string])) {
        foreach ($item in $InputObject) {
            if (Test-JsonContainsToken -InputObject $item -Token $Token) {
                return $true
            }
        }
        return $false
    }

    return ([string]$InputObject -eq $Token)
}

function Merge-WorkflowRegistryObject {
    param(
        [object]$TargetJson,
        [object]$SourceJson
    )

    $targetRegistry = ConvertTo-HashtableRecursive -InputObject $TargetJson
    $sourceRegistry = ConvertTo-HashtableRecursive -InputObject $SourceJson

    if ($null -eq $sourceRegistry) {
        throw "GRM workflow registry source is empty or invalid."
    }

    if ($null -eq $targetRegistry) {
        $targetRegistry = [ordered]@{}
    }

    if (-not ($targetRegistry -is [System.Collections.IDictionary])) {
        throw "Unsupported target workflow registry JSON shape."
    }

    if (-not ($sourceRegistry -is [System.Collections.IDictionary])) {
        throw "Unsupported source workflow registry JSON shape."
    }

    # Shape A: registry as object with top-level workflow ids, for example { "speckit": {...}, "grm": {...} }
    if (-not ($sourceRegistry.Contains("workflows"))) {
        foreach ($key in $sourceRegistry.Keys) {
            $targetRegistry[$key] = $sourceRegistry[$key]
        }
        return $targetRegistry
    }

    # Shape B: Spec Kit registry as { "schema_version": "1.0", "workflows": { "speckit": {...}, "grm": {...} } }
    if ($sourceRegistry.Contains("workflows") -and ($sourceRegistry["workflows"] -is [System.Collections.IDictionary])) {
        if (-not ($targetRegistry.Contains("schema_version")) -and $sourceRegistry.Contains("schema_version")) {
            $targetRegistry["schema_version"] = $sourceRegistry["schema_version"]
        }

        if (-not ($targetRegistry.Contains("workflows")) -or $null -eq $targetRegistry["workflows"]) {
            $targetRegistry["workflows"] = [ordered]@{}
        }

        if (-not ($targetRegistry["workflows"] -is [System.Collections.IDictionary])) {
            throw "Unsupported target workflow registry shape: workflows must be an object."
        }

        foreach ($workflowKey in $sourceRegistry["workflows"].Keys) {
            $targetRegistry["workflows"][$workflowKey] = $sourceRegistry["workflows"][$workflowKey]
        }

        return $targetRegistry
    }

    # Shape C: defensive support for { "workflows": [ { "id": "..." } ] } if future versions change format.
    if ($sourceRegistry.Contains("workflows") -and ($sourceRegistry["workflows"] -is [System.Collections.IEnumerable]) -and -not ($sourceRegistry["workflows"] -is [string])) {
        if (-not ($targetRegistry.Contains("workflows")) -or $null -eq $targetRegistry["workflows"]) {
            $targetRegistry["workflows"] = @()
        }

        $targetWorkflows = @($targetRegistry["workflows"])
        $sourceWorkflows = @($sourceRegistry["workflows"])

        foreach ($sourceWorkflow in $sourceWorkflows) {
            $sourceId = $null
            if ($sourceWorkflow -is [System.Collections.IDictionary]) {
                foreach ($candidateKey in @("id", "name", "key")) {
                    if ($sourceWorkflow.Contains($candidateKey)) {
                        $sourceId = [string]$sourceWorkflow[$candidateKey]
                        break
                    }
                }
            }

            if ([string]::IsNullOrWhiteSpace($sourceId)) {
                $targetWorkflows += $sourceWorkflow
                continue
            }

            $updated = $false
            for ($i = 0; $i -lt $targetWorkflows.Count; $i++) {
                $targetWorkflow = $targetWorkflows[$i]
                if ($targetWorkflow -is [System.Collections.IDictionary]) {
                    foreach ($candidateKey in @("id", "name", "key")) {
                        if ($targetWorkflow.Contains($candidateKey) -and ([string]$targetWorkflow[$candidateKey]) -eq $sourceId) {
                            $targetWorkflows[$i] = $sourceWorkflow
                            $updated = $true
                            break
                        }
                    }
                }
                if ($updated) { break }
            }

            if (-not $updated) {
                $targetWorkflows += $sourceWorkflow
            }
        }

        $targetRegistry["workflows"] = $targetWorkflows
        return $targetRegistry
    }

    throw "Unsupported workflow registry JSON shape."
}

function Install-GrmWorkflows {
    param(
        [string]$SourceRepoPath,
        [string]$TargetPath,
        [System.Collections.Generic.List[string]]$Warnings
    )

    $sourceWorkflowsPath = Join-Path $SourceRepoPath "presets/grm-corporate-governance/workflows"
    $targetWorkflowsPath = Join-Path $TargetPath ".specify/workflows"
    $sourceRegistryPath = Join-Path $sourceWorkflowsPath "workflow-registry.json"
    $targetRegistryPath = Join-Path $targetWorkflowsPath "workflow-registry.json"

    if (-not (Test-Path $sourceWorkflowsPath)) {
        throw "GRM workflows source not found: $sourceWorkflowsPath"
    }

    if (-not (Test-Path $sourceRegistryPath)) {
        throw "GRM workflow registry source not found: $sourceRegistryPath"
    }

    if (-not (Test-Path $targetWorkflowsPath)) {
        New-Item -ItemType Directory -Path $targetWorkflowsPath -Force | Out-Null
    }

    Get-ChildItem -Path $sourceWorkflowsPath -Directory | ForEach-Object {
        $destination = Join-Path $targetWorkflowsPath $_.Name
        Copy-Item -Path $_.FullName -Destination $destination -Recurse -Force
    }

    if (-not (Test-Path $targetRegistryPath)) {
        "{}" | Set-Content -Path $targetRegistryPath -Encoding UTF8
    }

    $sourceJson = Get-Content $sourceRegistryPath -Raw | ConvertFrom-Json
    $targetJson = Get-Content $targetRegistryPath -Raw | ConvertFrom-Json

    $mergedRegistry = Merge-WorkflowRegistryObject -TargetJson $targetJson -SourceJson $sourceJson
    $mergedRegistry | ConvertTo-Json -Depth 30 | Set-Content -Path $targetRegistryPath -Encoding UTF8

    $grmWorkflowPath = Join-Path $targetWorkflowsPath "grm/workflow.yml"
    if (-not (Test-Path $grmWorkflowPath)) {
        throw "GRM workflow was not installed correctly: $grmWorkflowPath"
    }

    $mergedRegistryJson = Get-Content $targetRegistryPath -Raw | ConvertFrom-Json

    if (-not (Test-JsonContainsToken -InputObject $mergedRegistryJson -Token "grm")) {
        throw "GRM workflow registry entry was not merged correctly."
    }

    if (-not (Test-JsonContainsToken -InputObject $mergedRegistryJson -Token "speckit")) {
        throw "Native speckit workflow registry entry is missing after merge."
    }

    $detectedWorkflowEntries = @()
    if ($mergedRegistryJson.PSObject.Properties.Name -contains "workflows") {
        $workflowNode = $mergedRegistryJson.workflows
        if ($workflowNode -is [System.Management.Automation.PSCustomObject]) {
            $detectedWorkflowEntries = @($workflowNode.PSObject.Properties.Name)
        }
        elseif ($workflowNode -is [System.Collections.IEnumerable] -and -not ($workflowNode -is [string])) {
            foreach ($workflow in @($workflowNode)) {
                if ($workflow.PSObject.Properties.Name -contains "id") { $detectedWorkflowEntries += [string]$workflow.id }
                elseif ($workflow.PSObject.Properties.Name -contains "name") { $detectedWorkflowEntries += [string]$workflow.name }
                elseif ($workflow.PSObject.Properties.Name -contains "key") { $detectedWorkflowEntries += [string]$workflow.key }
            }
        }
    }
    else {
        $detectedWorkflowEntries = @($mergedRegistryJson.PSObject.Properties.Name)
    }

    Write-Ok "GRM workflows installed and workflow registry merged"
    return $detectedWorkflowEntries
}

function New-InstallationReport {
    param(
        [string]$ReportPath,
        [string]$Status,
        [string]$ErrorMessage,
        [datetime]$StartTime,
        [datetime]$EndTime,
        [string]$RootPath,
        [string]$TargetPath,
        [string]$InstallMode,
        [string]$EffectiveMode,
        [string]$GitVersion,
        [string]$SpecKitVersion,
        [string]$SpecKitInitCommandForReport,
        [string]$InstalledRemote,
        [string]$InstalledBranch,
        [string]$InstalledCommit,
        [string]$SourceRepoPath,
        [bool]$KeepSourceCache,
        [string[]]$AgentFiles,
        [string[]]$PromptFiles,
        [string[]]$WorkflowEntries,
        [bool]$SamplesCopied,
        [bool]$DocsCopied,
        [bool]$ConstitutionCopied,
        [string[]]$Missing,
        [System.Collections.Generic.List[string]]$Warnings
    )

    $reportDirectory = Split-Path -Path $ReportPath -Parent
    if (-not [string]::IsNullOrWhiteSpace($reportDirectory) -and -not (Test-Path $reportDirectory)) {
        New-Item -ItemType Directory -Path $reportDirectory -Force | Out-Null
    }

    $agentLines = if ($AgentFiles.Count -gt 0) { ($AgentFiles | Sort-Object | ForEach-Object { "- $_" }) -join "`n" } else { "- none detected" }
    $promptLines = if ($PromptFiles.Count -gt 0) { ($PromptFiles | Sort-Object | ForEach-Object { "- $_" }) -join "`n" } else { "- none detected" }
    $workflowLines = if ($WorkflowEntries.Count -gt 0) { ($WorkflowEntries | Sort-Object | ForEach-Object { "- $_" }) -join "`n" } else { "- none detected" }
    $missingLines = if ($Missing.Count -gt 0) { ($Missing | ForEach-Object { "- $_" }) -join "`n" } else { "- none" }
    $warningLines = if ($Warnings.Count -gt 0) { ($Warnings | ForEach-Object { "- $_" }) -join "`n" } else { "- none" }
    $errorBlock = if ([string]::IsNullOrWhiteSpace($ErrorMessage)) { "- none" } else { "- $ErrorMessage" }

    $content = @"
# GRM Custom Spec Kit Installation Report

## Status

$Status

## Execution

| Field | Value |
|---|---|
| Started | $StartTime |
| Finished | $EndTime |
| Root | $RootPath |
| Target | $TargetPath |
| Requested install mode | $InstallMode |
| Effective install mode | $EffectiveMode |
| Git | $GitVersion |
| Spec Kit | $SpecKitVersion |
| Spec Kit init command | $SpecKitInitCommandForReport |

## GRM Customization Source

| Field | Value |
|---|---|
| Repository | $InstalledRemote |
| Branch | $InstalledBranch |
| Commit | $InstalledCommit |
| Cache path | $SourceRepoPath |
| Cache retained | $KeepSourceCache |

## Installed Runtime

### Agents

$agentLines

### Prompts

$promptLines

### Workflows

$workflowLines

## Supporting Assets

| Asset | Copied |
|---|---|
| samples | $SamplesCopied |
| docs | $DocsCopied |
| constitution | $ConstitutionCopied |

## Missing Items

$missingLines

## Warnings

$warningLines

## Error Details

$errorBlock
"@

    Set-Content -Path $ReportPath -Value $content -Encoding UTF8
}

if ([string]::IsNullOrWhiteSpace($TargetName)) {
    $TargetName = Read-Host "Nombre del nuevo directorio E2E"
}

if ([string]::IsNullOrWhiteSpace($TargetName)) {
    throw "TargetName is required. Example: .\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01"
}

if ($TargetName -match '[\\/:*?"<>|]') {
    throw "TargetName contains invalid path characters: $TargetName"
}

$StartTime = Get-Date
$Warnings = [System.Collections.Generic.List[string]]::new()
$Missing = @()
$AgentFiles = @()
$PromptFiles = @()
$DeployedArtifacts = [System.Collections.Generic.List[string]]::new()
$WorkflowEntries = @()
$SamplesCopied = $false
$DocsCopied = $false
$ConstitutionCopied = $false
$GitVersion = "unknown"
$SpecKitVersion = "unknown"
$SpecKitInitCommandForReport = "specify init --here --integration $Integration --script $ScriptType --force"
$CacheRoot = Join-Path $env:TEMP "grm-custom-spec-kit-cache"
$InstalledCommit = "unknown"
$InstalledRemote = $SourceRepoUrl
$InstalledBranch = $Branch
$SourceRepoPath = "unknown"
$TargetPath = "unknown"
$RootPath = "unknown"
$EffectiveMode = "not-started"
$ReportPath = "unknown"
$Status = "FAILED"
$CapturedErrorMessage = ""

try {
    Write-Step "Pre-flight checks"
    Assert-Command git
    Assert-Command specify

    $RootPath = (New-Item -ItemType Directory -Path $Root -Force).FullName
    $TargetPath = Join-Path $RootPath $TargetName
    $ReportPath = Join-Path $TargetPath "installation-report.md"
    $GitVersion = Get-CommandVersionSafe -CommandName git -Arguments @("--version")
    $SpecKitVersion = Get-CommandVersionSafe -CommandName specify -Arguments @("--version")

    Write-Ok "Pre-flight checks passed"

    Write-Step "Resolve target workspace policy"
    $EffectiveMode = Resolve-TargetWorkspacePolicy -TargetPath $TargetPath -InstallMode $InstallMode -Force:$Force
    Write-Ok "Effective install mode: $EffectiveMode"

    Write-Step "Prepare GRM customization source"
    if (Test-Path $CacheRoot) {
        Remove-Item -Path $CacheRoot -Recurse -Force
    }
    New-Item -ItemType Directory -Path $CacheRoot -Force | Out-Null
    $SourceRepoPath = Join-Path $CacheRoot "source"

    Invoke-GitChecked -Arguments @("clone", "--branch", $Branch, "--single-branch", $SourceRepoUrl, $SourceRepoPath) -ErrorMessage "Unable to clone GRM customization repository."
    Push-Location $SourceRepoPath
    try {
        $InstalledCommit = (& git rev-parse HEAD).Trim()
    }
    finally {
        Pop-Location
    }
    Write-Ok "GRM customization source cloned"

    if ($EffectiveMode -eq "CleanInstall") {
        Write-Step "Initialize Spec Kit runtime"
        Push-Location $TargetPath
        try {
            & specify init --here --integration $Integration --script $ScriptType --force
            if ($LASTEXITCODE -ne 0) {
                throw "Spec Kit initialization failed."
            }
        }
        finally {
            Pop-Location
        }
        Write-Ok "Spec Kit initialized with integration=$Integration and script=$ScriptType"

        if (-not $SkipGitInit) {
            Write-Step "Initialize Git repository"
            Push-Location $TargetPath
            try {
                if (-not (Test-Path (Join-Path $TargetPath ".git"))) {
                    Invoke-GitChecked -Arguments @("init") -ErrorMessage "Unable to initialize Git repository."
                }
                if ($CreateBranch) {
                    Invoke-GitChecked -Arguments @("checkout", "-B", $BranchName) -ErrorMessage "Unable to create or switch Git branch."
                }
            }
            finally {
                Pop-Location
            }
            Write-Ok "Git repository initialized"
        }
    }
    else {
        Write-Step "Update existing workspace"
        Write-Ok "Existing runtime preserved. Spec Kit init was not executed."
    }

    Write-Step "Apply GRM source-of-truth assets"
    $extensionFrom = Join-Path $SourceRepoPath "extensions/grm-corporate-workflow"
    $extensionTo = Join-Path $TargetPath "extensions/grm-corporate-workflow"
    Copy-DirectoryMerge -From $extensionFrom -To $extensionTo -Label "GRM corporate workflow extension" -Warnings $Warnings | Out-Null

    $presetFrom = Join-Path $SourceRepoPath "presets/grm-corporate-governance"
    $presetTo = Join-Path $TargetPath "presets/grm-corporate-governance"
    Copy-DirectoryMerge -From $presetFrom -To $presetTo -Label "GRM corporate governance preset" -Warnings $Warnings | Out-Null

    Write-Step "Deploy corporate agents and prompts (manifest-driven)"
    $agentsTo = Join-Path $TargetPath ".github/agents"
    $promptsTo = Join-Path $TargetPath ".github/prompts"
    Install-CorporateAgentsAndPrompts -SourceRepoPath $SourceRepoPath -TargetPath $TargetPath -Deployed $DeployedArtifacts

    Write-Step "Install GRM workflows"
    $WorkflowEntries = @(Install-GrmWorkflows -SourceRepoPath $SourceRepoPath -TargetPath $TargetPath -Warnings $Warnings)

    Write-Step "Copy supporting assets"
    $SamplesCopied = Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "samples") -To (Join-Path $TargetPath "samples") -Label "GRM samples" -Warnings $Warnings
    $DocsCopied = Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "docs") -To (Join-Path $TargetPath "docs") -Label "GRM docs" -Warnings $Warnings -ExcludeDirectoryNames @("sessions")

    $constitutionSource = Join-Path $SourceRepoPath "presets/grm-corporate-governance/memory/constitution.md"
    $constitutionTarget = Join-Path $TargetPath ".specify/memory/constitution.md"
    $ConstitutionCopied = Copy-FileIfExists -From $constitutionSource -To $constitutionTarget -Label "GRM corporate constitution" -Warnings $Warnings

    Write-Step "Validate installed runtime"
    $requiredPaths = @(
        ".github/agents",
        ".github/prompts",
        ".specify",
        ".specify/workflows",
        ".specify/workflows/speckit/workflow.yml",
        ".specify/workflows/grm/workflow.yml",
        ".specify/workflows/workflow-registry.json",
        "extensions/grm-corporate-workflow",
        "presets/grm-corporate-governance"
    )

    foreach ($relativePath in $requiredPaths) {
        $fullPath = Join-Path $TargetPath $relativePath
        if (-not (Test-Path $fullPath)) {
            $Missing += $relativePath
        }
    }

    $registryPath = Join-Path $TargetPath ".specify/workflows/workflow-registry.json"
    if (Test-Path $registryPath) {
        $registry = Get-Content $registryPath -Raw | ConvertFrom-Json
        if (-not (Test-JsonContainsToken -InputObject $registry -Token "speckit")) {
            $Missing += ".specify/workflows/workflow-registry.json:speckit"
        }
        if (-not (Test-JsonContainsToken -InputObject $registry -Token "grm")) {
            $Missing += ".specify/workflows/workflow-registry.json:grm"
        }
    }

    if (Test-Path $agentsTo) {
        $AgentFiles = @(Get-ChildItem -Path $agentsTo -File | Select-Object -ExpandProperty Name)
    }
    if (Test-Path $promptsTo) {
        $PromptFiles = @(Get-ChildItem -Path $promptsTo -File | Select-Object -ExpandProperty Name)
    }

    if ($Missing.Count -gt 0) {
        throw "Runtime validation failed. Missing items: $($Missing -join ', ')"
    }

    Write-Ok "Runtime validation passed"
    $Status = "SUCCESS"
}
catch {
    $CapturedErrorMessage = $_.Exception.Message
    Write-Host "`n[ERROR] Bootstrap failed: $CapturedErrorMessage" -ForegroundColor Red
    $Status = "FAILED"
}
finally {
    $EndTime = Get-Date

    if ($TargetPath -ne "unknown") {
        if ($ReportPath -eq "unknown") {
            $ReportPath = Join-Path $TargetPath "installation-report.md"
        }

        try {
            New-InstallationReport `
                -ReportPath $ReportPath `
                -Status $Status `
                -ErrorMessage $CapturedErrorMessage `
                -StartTime $StartTime `
                -EndTime $EndTime `
                -RootPath $RootPath `
                -TargetPath $TargetPath `
                -InstallMode $InstallMode `
                -EffectiveMode $EffectiveMode `
                -GitVersion $GitVersion `
                -SpecKitVersion $SpecKitVersion `
                -SpecKitInitCommandForReport $SpecKitInitCommandForReport `
                -InstalledRemote $InstalledRemote `
                -InstalledBranch $InstalledBranch `
                -InstalledCommit $InstalledCommit `
                -SourceRepoPath $SourceRepoPath `
                -KeepSourceCache:$KeepSourceCache `
                -AgentFiles $AgentFiles `
                -PromptFiles $PromptFiles `
                -WorkflowEntries $WorkflowEntries `
                -SamplesCopied:$SamplesCopied `
                -DocsCopied:$DocsCopied `
                -ConstitutionCopied:$ConstitutionCopied `
                -Missing $Missing `
                -Warnings $Warnings
            Write-Ok "Installation report generated: $ReportPath"
        }
        catch {
            Write-Warn2 "Could not generate installation report: $($_.Exception.Message)"
        }
    }

    if (-not $KeepSourceCache -and (Test-Path $CacheRoot)) {
        try {
            Remove-Item -Path $CacheRoot -Recurse -Force
        }
        catch {
            Write-Warn2 "Could not remove source cache: $CacheRoot"
        }
    }
}

if ($Status -ne "SUCCESS") {
    exit 1
}

Write-Ok "Bootstrap completed"
exit 0
