<#
.SYNOPSIS
Bootstrap a clean E2E validation workspace for GRM Custom Spec Kit.

.DESCRIPTION
Creates a new validation directory, initializes a clean Spec Kit runtime in deterministic mode,
applies the GRM customization from the official Git repository, validates the resulting repository
structure and runtime files, and generates an installation report.

Deterministic Spec Kit initialization:
- specify init --here --integration copilot --script ps --force
- Avoids interactive TUI menus.
- Ensures GitHub Copilot + PowerShell are selected explicitly.

Runtime merge policy:
- Does NOT delete .github or .specify generated by Spec Kit.
- Copies GRM runtime files over the clean runtime where names match.
- Preserves additional standard Spec Kit runtime files introduced by the installed version.
- Applies governance override agents after standard GRM runtime agents.
- Copies supporting assets such as samples.

.EXAMPLES
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01 -Force
.\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01 -Branch main -KeepSourceCache
#>

[CmdletBinding()]
param(
    [string]$Root = "C:\dev\proys",
    [string]$TargetName,
    [string]$SourceRepoUrl = "https://github.com/sesanchezromeu/grm-custom-spec-kit.git",
    [string]$Branch = "main",
    [string]$Integration = "copilot",
    [string]$ScriptType = "ps",
    [switch]$Force,
    [switch]$KeepSourceCache,
    [switch]$SkipGitInit,
    [switch]$CreateBranch,
    [string]$BranchName = "chore/e2e-clean-install"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([string]$Message)
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Write-Warn2 {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Assert-Command {
    param([string]$CommandName)
    if (-not (Get-Command $CommandName -ErrorAction SilentlyContinue)) {
        throw "Required command not found in PATH: $CommandName"
    }
}

function Resolve-AbsoluteDirectory {
    param([string]$PathValue, [string]$Label)
    if (-not (Test-Path $PathValue)) {
        throw "$Label not found: $PathValue"
    }
    return (Resolve-Path $PathValue).Path
}

function Get-CommandVersionSafe {
    param([string]$CommandName, [string[]]$Arguments)
    try {
        $output = & $CommandName @Arguments 2>&1 | Select-Object -First 1
        if ([string]::IsNullOrWhiteSpace($output)) {
            return "unknown"
        }
        return ($output | Out-String).Trim()
    }
    catch {
        return "unknown"
    }
}

function Copy-DirectoryMerge {
    param(
        [string]$From,
        [string]$To,
        [string]$Label,
        [System.Collections.Generic.List[string]]$Warnings
    )

    if (-not (Test-Path $From)) {
        $msg = "$Label not found in source, skipping: $From"
        Write-Warn2 $msg
        if ($Warnings) { $Warnings.Add($msg) }
        return $false
    }

    New-Item -ItemType Directory -Force -Path $To | Out-Null
    Copy-Item -Path (Join-Path $From "*") -Destination $To -Recurse -Force
    Write-Ok "$Label copied/merged"
    return $true
}

function Copy-FileIfExists {
    param(
        [string]$From,
        [string]$To,
        [string]$Label,
        [System.Collections.Generic.List[string]]$Warnings
    )

    if (-not (Test-Path $From)) {
        $msg = "$Label not found in source, skipping: $From"
        Write-Warn2 $msg
        if ($Warnings) { $Warnings.Add($msg) }
        return $false
    }

    $parent = Split-Path -Parent $To
    if ($parent) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    Copy-Item -Path $From -Destination $To -Force
    Write-Ok "$Label copied"
    return $true
}

function Invoke-GitChecked {
    param([string[]]$Arguments, [string]$ErrorMessage)
    & git @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw $ErrorMessage
    }
}

if ([string]::IsNullOrWhiteSpace($TargetName)) {
    $TargetName = Read-Host "Nombre del nuevo directorio E2E"
}

if ([string]::IsNullOrWhiteSpace($TargetName)) {
    throw "TargetName is required. Example: .\bootstrap-grm-e2e.ps1 -TargetName e2e-demo-01"
}

if ($TargetName -match '[\\/:*?"<>|]') {
    throw "TargetName contains invalid path characters: $TargetName"
}

$StartTime = Get-Date
$Warnings = [System.Collections.Generic.List[string]]::new()
$Missing = @()
$AgentFiles = @()
$PromptFiles = @()
$SamplesCopied = $false
$DocsCopied = $false    
$ConstitutionCopied = $false
$GitVersion = "unknown"
$SpecKitVersion = "unknown"
$SpecKitInitCommandForReport = "specify init --here --integration $Integration --script $ScriptType --force"
$CacheRoot = Join-Path $env:TEMP "grm-custom-spec-kit-cache"
$InstalledCommit = "unknown"
$InstalledRemote = $SourceRepoUrl
$InstalledBranch = $Branch
$SourceRepoPath = "unknown"
$TargetPath = "unknown"
$RootPath = "unknown"

try {
    Write-Step "Pre-flight checks"
    Assert-Command git
    Assert-Command specify

    $RootPath = Resolve-AbsoluteDirectory -PathValue $Root -Label "Root directory"
    $TargetPath = Join-Path $RootPath $TargetName
    $GitVersion = Get-CommandVersionSafe -CommandName "git" -Arguments @("--version")
    $SpecKitVersion = Get-CommandVersionSafe -CommandName "specify" -Arguments @("--version")

    Write-Host "Root: $RootPath"
    Write-Host "TargetPath: $TargetPath"
    Write-Host "SourceRepoUrl: $SourceRepoUrl"
    Write-Host "Branch: $Branch"
    Write-Host "Git: $GitVersion"
    Write-Host "Spec Kit: $SpecKitVersion"
    Write-Host "Spec Kit init mode: integration=$Integration, script=$ScriptType, force=true"

    Write-Step "Preparing GRM customization repository"
    & git ls-remote --heads $SourceRepoUrl $Branch | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Cannot access repository or branch: $SourceRepoUrl [$Branch]"
    }

    if (-not (Test-Path $CacheRoot)) {
        Write-Host "Cloning repository into cache: $CacheRoot" -ForegroundColor Cyan
        Invoke-GitChecked -Arguments @("clone", "--branch", $Branch, "--single-branch", $SourceRepoUrl, $CacheRoot) -ErrorMessage "Repository clone failed: $SourceRepoUrl"
    }
    else {
        Write-Host "Refreshing cached repository: $CacheRoot" -ForegroundColor Cyan
        Push-Location $CacheRoot
        try {
            Invoke-GitChecked -Arguments @("remote", "set-url", "origin", $SourceRepoUrl) -ErrorMessage "git remote set-url failed"
            Invoke-GitChecked -Arguments @("fetch", "origin", $Branch) -ErrorMessage "git fetch failed"
            Invoke-GitChecked -Arguments @("checkout", $Branch) -ErrorMessage "git checkout failed"
            Invoke-GitChecked -Arguments @("reset", "--hard", "origin/$Branch") -ErrorMessage "git reset failed"
            Invoke-GitChecked -Arguments @("clean", "-fdx") -ErrorMessage "git clean failed"
        }
        finally {
            Pop-Location
        }
    }

    $SourceRepoPath = (Resolve-Path $CacheRoot).Path
    $InstalledCommit = (& git -C $SourceRepoPath rev-parse HEAD 2>$null | Out-String).Trim()
    if ([string]::IsNullOrWhiteSpace($InstalledCommit)) {
        $InstalledCommit = "unknown"
    }

    Write-Host "SourceRepoPath: $SourceRepoPath"
    Write-Host "InstalledCommit: $InstalledCommit"

    $requiredSourcePaths = @(
        (Join-Path $SourceRepoPath "extensions\grm-corporate-workflow"),
        (Join-Path $SourceRepoPath "presets\grm-corporate-governance")
    )

    foreach ($sourcePath in $requiredSourcePaths) {
        if (-not (Test-Path $sourcePath)) {
            throw "Required source path not found: $sourcePath"
        }
    }

    Write-Ok "Required commands and source paths are available"

    Write-Step "Create clean target directory: $TargetPath"
    if (Test-Path $TargetPath) {
        if ($Force) {
            Write-Warn2 "Target exists and -Force was provided. Removing: $TargetPath"
            Remove-Item -Path $TargetPath -Recurse -Force
        }
        else {
            throw "Target directory already exists: $TargetPath. Use a new -TargetName or -Force to recreate it."
        }
    }

    New-Item -ItemType Directory -Force -Path $TargetPath | Out-Null
    Write-Ok "Target directory created"

    Push-Location $TargetPath
    try {
        Write-Step "Initialize clean Spec Kit runtime in deterministic mode"
        & specify init --here --integration $Integration --script $ScriptType --force
        if ($LASTEXITCODE -ne 0) {
            throw "specify init failed with exit code $LASTEXITCODE"
        }
        Write-Ok "Spec Kit initialized with integration=$Integration and script=$ScriptType"

        if (-not $SkipGitInit) {
            Write-Step "Ensure git repository exists"
            if (-not (Test-Path (Join-Path $TargetPath ".git"))) {
                Invoke-GitChecked -Arguments @("init") -ErrorMessage "git init failed"
                Write-Ok "Git repository initialized"
            }
            else {
                Write-Ok "Git repository already exists"
            }

            if ($CreateBranch) {
                Invoke-GitChecked -Arguments @("checkout", "-B", $BranchName) -ErrorMessage "git checkout branch failed"
                Write-Ok "Branch created/selected: $BranchName"
            }
        }

        Write-Step "Apply GRM customization"

        [void](Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "extensions\grm-corporate-workflow") -To (Join-Path $TargetPath "extensions\grm-corporate-workflow") -Label "GRM corporate workflow extension" -Warnings $Warnings)
        [void](Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "presets\grm-corporate-governance") -To (Join-Path $TargetPath "presets\grm-corporate-governance") -Label "GRM corporate governance preset" -Warnings $Warnings)
        [void](Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "extensions\grm-corporate-workflow\agents") -To (Join-Path $TargetPath ".github\agents") -Label "GRM runtime agents" -Warnings $Warnings)
        [void](Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "presets\grm-corporate-governance\agents") -To (Join-Path $TargetPath ".github\agents") -Label "GRM governance override agents" -Warnings $Warnings)
        [void](Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "extensions\grm-corporate-workflow\prompts") -To (Join-Path $TargetPath ".github\prompts") -Label "GRM runtime prompts" -Warnings $Warnings)

        $SamplesCopied = Copy-DirectoryMerge -From (Join-Path $SourceRepoPath "samples") -To (Join-Path $TargetPath "samples") -Label "GRM samples" -Warnings $Warnings
        $SamplesCopied = [bool](Test-Path (Join-Path $TargetPath "samples"))

        $DocsSource = Join-Path $SourceRepoPath "docs"
        $DocsTarget = Join-Path $TargetPath "docs"

        if (Test-Path $DocsSource) { 
            Copy-DirectoryMerge -From ($DocsSource) -To ($DocsTarget) -Label "GRM docs" -Warnings $Warnings | Out-Null
            $DocsCopied = $true
        }
        else {
            [void]$Warnings.Add("docs source directory not found: $DocsSource")
        }

        $ConstitutionCopied = Copy-FileIfExists -From (Join-Path $SourceRepoPath "presets\grm-corporate-governance\memory\constitution.md") -To (Join-Path $TargetPath ".specify\memory\constitution.md") -Label "GRM corporate constitution" -Warnings $Warnings
        $ConstitutionCopied = [bool]$ConstitutionCopied

        Write-Step "Validate installed runtime"

        $expectedAgents = @(
            "corp.load.agent.md",
            "corp.assess.agent.md",
            "corp.plan.agent.md",
            "corp.doc.agent.md",
            "speckit.specify.agent.md",
            "speckit.clarify.agent.md"
        )

        foreach ($agent in $expectedAgents) {
            $path = Join-Path $TargetPath ".github\agents\$agent"
            if (Test-Path $path) {
                $AgentFiles += $agent
            }
            else {
                $Missing += ".github/agents/$agent"
            }
        }

        $promptPath = Join-Path $TargetPath ".github\prompts"
        if (Test-Path $promptPath) {
            $PromptFiles = Get-ChildItem -Path $promptPath -File -Filter "*.md" | Select-Object -ExpandProperty Name
        }
        else {
            $Missing += ".github/prompts"
        }

        if (-not (Test-Path (Join-Path $TargetPath ".specify\memory\constitution.md"))) {
            $Missing += ".specify/memory/constitution.md"
        }

        if (-not (Test-Path (Join-Path $TargetPath "samples"))) {
            $Missing += "samples"
        }

        $specifyOverridePath = Join-Path $TargetPath ".github\agents\speckit.specify.agent.md"
        $clarifyOverridePath = Join-Path $TargetPath ".github\agents\speckit.clarify.agent.md"

        if (Test-Path $specifyOverridePath) {
            $specifyOverrideSize = (Get-Item $specifyOverridePath).Length
            if ($specifyOverrideSize -gt 5000) {
                $Missing += ".github/agents/speckit.specify.agent.md governance override not applied"
            }
        }

        if (Test-Path $clarifyOverridePath) {
            $clarifyOverrideSize = (Get-Item $clarifyOverridePath).Length
            if ($clarifyOverrideSize -gt 5000) {
                $Missing += ".github/agents/speckit.clarify.agent.md governance override not applied"
            }
        }

        if ($Missing.Count -eq 0) {
            Write-Ok "Runtime validation passed"
        }
        else {
            Write-Warn2 "Runtime validation completed with missing items"
        }
    }
    finally {
        Pop-Location
    }

    $EndTime = Get-Date
    $Status = if ($Missing.Count -eq 0) { "SUCCESS" } else { "SUCCESS_WITH_WARNINGS" }
    $ReportPath = Join-Path $TargetPath "installation-report.md"

    $AgentLines = if ($AgentFiles.Count -gt 0) { ($AgentFiles | ForEach-Object { "- $_" }) -join "`n" } else { "None" }
    $PromptLines = if ($PromptFiles.Count -gt 0) { ($PromptFiles | ForEach-Object { "- $_" }) -join "`n" } else { "None" }
    $MissingLines = if ($Missing.Count -gt 0) { ($Missing | ForEach-Object { "- $_" }) -join "`n" } else { "None" }
    $WarningLines = if ($Warnings.Count -gt 0) { ($Warnings | ForEach-Object { "- $_" }) -join "`n" } else { "None" }

    $report = @"
# GRM Custom Spec Kit Installation Report

## Status

$Status

## Execution

| Field | Value |
|---|---|
| Started | $StartTime |
| Finished | $EndTime |
| Root | $RootPath |
| Target | $TargetPath |
| Git | $GitVersion |
| Spec Kit | $SpecKitVersion |
| Spec Kit init command | $SpecKitInitCommandForReport |

## GRM Customization Source

| Field | Value |
|---|---|
| Repository | $InstalledRemote |
| Branch | $InstalledBranch |
| Commit | $InstalledCommit |
| Cache path | $SourceRepoPath |
| Cache retained | $KeepSourceCache |

## Installed Runtime

### Agents

$AgentLines

### Prompts

$PromptLines

### Supporting Assets

| Asset | Copied |
|---|---|
| samples | $SamplesCopied |

### Constitution

Copied: $ConstitutionCopied

## Missing Items

$MissingLines

## Warnings

$WarningLines
"@

    Set-Content -Path $ReportPath -Value $report -Encoding UTF8
    Write-Ok "Installation report generated: $ReportPath"

    if (-not $KeepSourceCache) {
        Write-Step "Removing temporary repository cache"
        Remove-Item -Path $CacheRoot -Recurse -Force -ErrorAction SilentlyContinue
        Write-Ok "Temporary repository cache removed"
    }

    Write-Step "Bootstrap completed"
    Write-Ok "Target workspace ready: $TargetPath"
}
catch {
    Write-Host "`n[ERROR] Bootstrap failed: $($_.Exception.Message)" -ForegroundColor Red
    throw
}
